line-length = 100
target-version = "py310"
preview = true
extend-include = ["*.md"]

[lint]
select = ["E", "F", "I", "UP", "B", "ASYNC"]
ignore = ["E501", "UP006", "UP007"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
