#!/usr/bin/env python3

"""Bounded Gate E corpus inspection and tiny candidate-build smoke.

This is intentionally a small, source-local utility.  It streams at most the
configured row cap from an exact Hugging Face revision, writes a compact report
plus short review snippets under a Git-ignored directory, and can exercise a
tiny checkpoint/resume/atomic-publication candidate build.  It does not train a
tokenizer, estimate tokens, build production quotas/shards, or implement the
archived Python P1/manual-review workflow.
"""

from __future__ import annotations

import argparse
import ast
from collections import Counter
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import math
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys
import time
from typing import Any
import unicodedata
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen
import uuid

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOOL_SCHEMA_VERSION = "petitgpt-corpus-gate-e-v2"
FILTER_VERSION = "petitgpt-basic-corpus-filter-v1"
MAX_INSPECTION_DOCUMENTS = 1_000
MAX_SMOKE_DOCUMENTS = 32
MAX_SMOKE_SCANNED = 1_000
DATASET_SERVER_ROWS_URL = "https://datasets-server.huggingface.co/rows"
DATASET_SERVER_FILTER_URL = "https://datasets-server.huggingface.co/filter"
DATASET_SERVER_MAX_WINDOWS = 10
DATASET_SERVER_MAX_RESPONSE_BYTES = 32 * 1024 * 1024
DATASET_SERVER_MAX_TOTAL_BYTES = 256 * 1024 * 1024
DATASET_SERVER_TIMEOUT_SECONDS = 60.0
DATASET_SERVER_MAX_ATTEMPTS = 3
MIN_ACCEPTED_FOR_GATE_E = 20
_REVISION_RE = re.compile(r"[0-9a-f]{40}")
_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "generated by",
    "generated file",
)
_VENDOR_PARTS = frozenset({
    "3rdparty",
    "deps",
    "external",
    "node_modules",
    "site-packages",
    "third_party",
    "thirdparty",
    "vendor",
    "vendored",
})


class GateEError(RuntimeError):
    """A fail-closed Gate E contract error."""


class PlannedInterruption(RuntimeError):
    """A deliberate candidate-smoke interruption after a durable checkpoint."""


@dataclass(frozen=True)
class SourceSpec:
    key: str
    dataset: str
    dataset_config: str
    split: str
    revision: str
    inspection_cap: int
    required_schema: tuple[tuple[str, str], ...]
    text_field: str = "text"
    quality_field: str | None = None
    minimum_quality: float | None = None
    language_field: str | None = None
    language_value: str | None = None
    minimum_bytes: int = 200
    maximum_bytes: int = 200_000
    review_minimum_quality: float | None = None
    review_minimum_bytes: int | None = None
    review_maximum_bytes: int | None = None
    review_scope: str = "basic_filter_outcome"
    dataset_server_where: str | None = None
    python_gate: bool = False
    volume_rows: int | None = None
    volume_rows_basis: str = "unavailable"
    card_license_fact: str | tuple[str, ...] | None = None


def _schema(*items: tuple[str, str]) -> tuple[tuple[str, str], ...]:
    return tuple(sorted(items))


SOURCE_SPECS: dict[str, SourceSpec] = {
    "fineweb_edu_dedup": SourceSpec(
        key="fineweb_edu_dedup",
        dataset="HuggingFaceTB/smollm-corpus",
        dataset_config="fineweb-edu-dedup",
        split="train",
        revision="3ba9d605774198c5868892d7a8deda78031a781f",
        inspection_cap=500,
        required_schema=_schema(
            ("id", "string"),
            ("metadata.date", "timestamp[s]"),
            ("metadata.dump", "string"),
            ("metadata.file_path", "string"),
            ("metadata.int_score", "int64"),
            ("metadata.language", "string"),
            ("metadata.language_score", "float64"),
            ("metadata.score", "float64"),
            ("metadata.token_count", "int64"),
            ("metadata.url", "string"),
            ("text", "string"),
        ),
        quality_field="metadata.int_score",
        minimum_quality=3,
        review_minimum_quality=4,
        review_scope="stage_b_quality_boundary",
        language_field="metadata.language",
        language_value="en",
        volume_rows=190_168_005,
        volume_rows_basis="pinned dataset-server exact row count",
        card_license_fact="odc-by",
    ),
    "dclm_edu": SourceSpec(
        key="dclm_edu",
        dataset="HuggingFaceTB/dclm-edu",
        dataset_config="default",
        split="train",
        revision="dbad8ad71224482740cd9c9d353591adbf62fe04",
        inspection_cap=500,
        required_schema=_schema(
            ("edu_int_score", "int64"),
            ("edu_score", "float64"),
            ("fasttext_score", "float64"),
            ("id", "string"),
            ("language", "string"),
            ("language_score", "float64"),
            ("text", "string"),
            ("url", "string"),
        ),
        quality_field="edu_int_score",
        minimum_quality=3,
        language_field="language",
        language_value="en",
        volume_rows=1_000_856_429,
        volume_rows_basis="pinned dataset card estimate; not viewer partial row count",
        card_license_fact="cc-by-4.0",
    ),
    "finewiki_en": SourceSpec(
        key="finewiki_en",
        dataset="HuggingFaceFW/finewiki",
        dataset_config="en",
        split="train",
        revision="8bd13e72e6a002407649b3e898535f42ceb1aeb9",
        inspection_cap=500,
        required_schema=_schema(
            ("bytes_html", "int64"),
            ("date_modified", "string"),
            ("has_math", "bool"),
            ("id", "string"),
            ("in_language", "string"),
            ("infoboxes", "string"),
            ("page_id", "int64"),
            ("text", "string"),
            ("title", "string"),
            ("url", "string"),
            ("version", "int64"),
            ("wikidata_id", "string"),
            ("wikiname", "string"),
            ("wikitext", "string"),
        ),
        language_field="in_language",
        language_value="en",
        review_minimum_bytes=1_000,
        review_maximum_bytes=100_000,
        review_scope="bounded_article_length_boundary",
        volume_rows=6_614_655,
        volume_rows_basis="pinned dataset-server exact row count",
        card_license_fact=("cc-by-sa-4.0", "gfdl"),
    ),
    "stackv2_python": SourceSpec(
        key="stackv2_python",
        dataset="common-pile/stackv2_edu_filtered",
        dataset_config="default",
        split="train",
        revision="c354dbe88469a1153e97c6a63ac50591849654de",
        inspection_cap=1_000,
        required_schema=_schema(
            ("added", "string"),
            ("created", "timestamp[s]"),
            ("id", "string"),
            ("int_score", "int64"),
            ("metadata.blob_id", "string"),
            ("metadata.detected_licenses", "list[string]"),
            ("metadata.is_generated", "bool"),
            ("metadata.is_vendor", "bool"),
            ("metadata.language", "string"),
            ("metadata.length_bytes", "int64"),
            ("metadata.path", "string"),
            ("metadata.src_encoding", "string"),
            ("score", "float64"),
            ("source", "string"),
            ("text", "string"),
        ),
        quality_field="int_score",
        language_field="metadata.language",
        language_value="Python",
        maximum_bytes=100_000,
        dataset_server_where="\"metadata.language\"='Python'",
        python_gate=True,
        volume_rows=69_588_607,
        volume_rows_basis=(
            "pinned card document count; viewer conversion is partial and disagrees"
        ),
        card_license_fact=None,
    ),
}


@dataclass(frozen=True)
class LoadedSource:
    rows: Iterable[Mapping[str, Any]]
    resolved_revision: str
    live_schema: Mapping[str, str]
    transport: str
    response_bytes: int = 0
    request_count: int = 0
    reported_rows: int | None = None
    partial: bool | None = None
    sample_windows: tuple[tuple[int, int], ...] = ()


@dataclass(frozen=True)
class InspectionConfig:
    source: SourceSpec
    output_dir: Path
    cache_dir: Path
    documents: int
    accepted_snippets: int = 25
    rejected_snippets: int = 12
    snippet_characters: int = 400
    max_wall_seconds: float = 1_800.0


@dataclass(frozen=True)
class SmokeConfig:
    source: SourceSpec
    inspection_report: Path
    output_dir: Path
    cache_dir: Path
    target_documents: int = 8
    max_scanned: int = 100
    stop_after_documents: int | None = None
    max_wall_seconds: float = 1_800.0


SourceLoader = Callable[[SourceSpec, Path, int], LoadedSource]


def _canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _git_head() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _ensure_revision(value: str) -> str:
    if not _REVISION_RE.fullmatch(value):
        raise GateEError("source revision must be an exact lowercase 40-hex commit")
    return value


def _ensure_under_workspace(path: Path) -> Path:
    resolved = path.resolve(strict=False)
    try:
        resolved.relative_to(PROJECT_ROOT)
    except ValueError as exc:
        raise GateEError("all Gate E paths must remain under the repository") from exc
    return resolved


def _ensure_git_ignored(path: Path) -> None:
    resolved = _ensure_under_workspace(path)
    relative = resolved.relative_to(PROJECT_ROOT)
    result = subprocess.run(
        ["git", "check-ignore", "--quiet", "--no-index", "--", str(relative)],
        cwd=PROJECT_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise GateEError(f"Gate E output/cache path is not Git-ignored: {relative}")


def _validate_inspection_config(config: InspectionConfig, staging: Path) -> None:
    _ensure_revision(config.source.revision)
    if not 1 <= config.documents <= config.source.inspection_cap:
        raise GateEError(
            f"documents must be in [1, {config.source.inspection_cap}] for {config.source.key}"
        )
    if not 20 <= config.accepted_snippets <= 30:
        raise GateEError("accepted_snippets must be in [20, 30]")
    if not 10 <= config.rejected_snippets <= 15:
        raise GateEError("rejected_snippets must be in [10, 15]")
    if not 1 <= config.snippet_characters <= 1_000:
        raise GateEError("snippet_characters must be in [1, 1000]")
    if not math.isfinite(config.max_wall_seconds) or config.max_wall_seconds <= 0:
        raise GateEError("max_wall_seconds must be positive")
    for path in (config.output_dir, config.cache_dir, staging):
        _ensure_git_ignored(path)


def _validate_smoke_config(config: SmokeConfig, staging: Path) -> None:
    _ensure_revision(config.source.revision)
    if not 1 <= config.target_documents <= MAX_SMOKE_DOCUMENTS:
        raise GateEError(f"target_documents must be in [1, {MAX_SMOKE_DOCUMENTS}]")
    if not config.target_documents <= config.max_scanned <= MAX_SMOKE_SCANNED:
        raise GateEError(f"max_scanned must be in [target_documents, {MAX_SMOKE_SCANNED}]")
    if config.stop_after_documents is not None and not (
        1 <= config.stop_after_documents < config.target_documents
    ):
        raise GateEError("stop_after_documents must be positive and below target_documents")
    if not math.isfinite(config.max_wall_seconds) or config.max_wall_seconds <= 0:
        raise GateEError("max_wall_seconds must be positive")
    for path in (
        config.inspection_report,
        config.inspection_report.with_name("review_snippets.jsonl"),
        config.output_dir,
        config.cache_dir,
        staging,
    ):
        _ensure_git_ignored(path)


def _configure_hf_cache(cache_dir: Path) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    os.environ["HF_HOME"] = str(cache_dir / "hf-home")
    os.environ["HF_DATASETS_CACHE"] = str(cache_dir / "datasets")
    os.environ["HUGGINGFACE_HUB_CACHE"] = str(cache_dir / "hub")
    os.environ.setdefault("HF_HUB_ETAG_TIMEOUT", "60")
    os.environ.setdefault("HF_HUB_DOWNLOAD_TIMEOUT", "60")


def _feature_type(feature: Any) -> str:
    if hasattr(feature, "feature"):
        return f"list[{_feature_type(feature.feature)}]"
    if hasattr(feature, "dtype"):
        return str(feature.dtype)
    return feature.__class__.__name__


def _flatten_features(features: Mapping[str, Any], prefix: str = "") -> dict[str, str]:
    flattened: dict[str, str] = {}
    for key, feature in features.items():
        path = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(feature, Mapping):
            flattened.update(_flatten_features(feature, path))
        else:
            flattened[path] = _feature_type(feature)
    return dict(sorted(flattened.items()))


def _server_feature_entries(feature: Any, prefix: str) -> dict[str, str]:
    if not isinstance(feature, Mapping):
        raise GateEError(f"Dataset Server feature is not an object: {prefix}")
    dtype = feature.get("dtype")
    if isinstance(dtype, str):
        return {prefix: dtype}
    nested = feature.get("feature")
    if nested is not None:
        nested_entries = _server_feature_entries(nested, prefix)
        if set(nested_entries) != {prefix}:
            raise GateEError(f"nested structured lists are unsupported: {prefix}")
        return {prefix: f"list[{nested_entries[prefix]}]"}
    ignored_keys = {"_type", "id", "length"}
    children = {str(key): value for key, value in feature.items() if key not in ignored_keys}
    if not children:
        raise GateEError(f"Dataset Server feature type is unsupported: {prefix}")
    flattened: dict[str, str] = {}
    for name, child in children.items():
        flattened.update(_server_feature_entries(child, f"{prefix}.{name}"))
    return flattened


def _server_schema(features: Any) -> dict[str, str]:
    if not isinstance(features, list) or not features:
        raise GateEError("Dataset Server response is missing features")
    flattened: dict[str, str] = {}
    for index, record in enumerate(features):
        if not isinstance(record, Mapping):
            raise GateEError("Dataset Server feature record is invalid")
        if record.get("feature_idx") != index:
            raise GateEError("Dataset Server feature indexes are not canonical")
        name = record.get("name")
        if not isinstance(name, str) or not name:
            raise GateEError("Dataset Server feature name is invalid")
        entries = _server_feature_entries(record.get("type"), name)
        if set(flattened).intersection(entries):
            raise GateEError("Dataset Server feature paths collide")
        flattened.update(entries)
    return dict(sorted(flattened.items()))


def _stratified_windows(total_rows: int, documents: int) -> tuple[tuple[int, int], ...]:
    if type(total_rows) is not int or total_rows < documents:
        raise GateEError("Dataset Server does not expose enough rows for the inspection cap")
    if documents == 1:
        return ((0, 1),)
    remaining = documents - 1
    window_count = min(DATASET_SERVER_MAX_WINDOWS, remaining)
    base_length, extra = divmod(remaining, window_count)
    lengths = [base_length + (1 if index < extra else 0) for index in range(window_count)]
    available = total_rows - 1
    windows: list[tuple[int, int]] = [(0, 1)]
    for index, length in enumerate(lengths):
        stratum_start = 1 + index * available // window_count
        stratum_end = 1 + (index + 1) * available // window_count
        if stratum_end - stratum_start < length:
            raise GateEError("Dataset Server strata are too small for a non-overlapping sample")
        offset = stratum_start + (stratum_end - stratum_start - length) // 2
        windows.append((offset, length))
    if sum(length for _, length in windows) != documents:
        raise AssertionError("Dataset Server windows must equal the requested document cap")
    return tuple(windows)


def _dataset_server_request(
    source: SourceSpec,
    *,
    offset: int,
    length: int,
    opener: Callable[..., Any],
    sleeper: Callable[[float], None],
) -> tuple[dict[str, Any], int, int]:
    if type(offset) is not int or offset < 0:
        raise GateEError("Dataset Server offset is invalid")
    if type(length) is not int or not 1 <= length <= 100:
        raise GateEError("Dataset Server length exceeds the bounded API contract")
    query_parameters: dict[str, str | int] = {
        "dataset": source.dataset,
        "config": source.dataset_config,
        "split": source.split,
        "offset": offset,
        "length": length,
    }
    base_url = DATASET_SERVER_ROWS_URL
    if source.dataset_server_where is not None:
        query_parameters["where"] = source.dataset_server_where
        base_url = DATASET_SERVER_FILTER_URL
    query = urlencode(query_parameters)
    headers = {"User-Agent": "PetitGPT-Gate-E/2"}
    token = os.environ.get("HF_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = Request(f"{base_url}?{query}", headers=headers)
    last_error: BaseException | None = None
    for attempt in range(DATASET_SERVER_MAX_ATTEMPTS):
        try:
            with opener(request, timeout=DATASET_SERVER_TIMEOUT_SECONDS) as response:
                resolved_revision = response.headers.get("x-revision")
                if resolved_revision != source.revision:
                    raise GateEError("Dataset Server x-revision does not match the frozen revision")
                declared_length = response.headers.get("content-length")
                if declared_length is not None:
                    try:
                        declared_bytes = int(declared_length)
                    except ValueError as exc:
                        raise GateEError("Dataset Server Content-Length is invalid") from exc
                    if declared_bytes > DATASET_SERVER_MAX_RESPONSE_BYTES:
                        raise GateEError("Dataset Server response exceeds the per-call byte cap")
                raw = response.read(DATASET_SERVER_MAX_RESPONSE_BYTES + 1)
            if len(raw) > DATASET_SERVER_MAX_RESPONSE_BYTES:
                raise GateEError("Dataset Server response exceeds the per-call byte cap")
            try:
                payload = json.loads(raw.decode("utf-8", errors="strict"))
            except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                raise GateEError("Dataset Server response is not strict UTF-8 JSON") from exc
            if not isinstance(payload, dict):
                raise GateEError("Dataset Server response is not an object")
            return payload, len(raw), attempt + 1
        except GateEError:
            raise
        except HTTPError as exc:
            if exc.code < 500 and exc.code != 429:
                raise GateEError(f"Dataset Server returned HTTP {exc.code}") from exc
            last_error = exc
        except (URLError, TimeoutError, OSError) as exc:
            last_error = exc
        if attempt + 1 < DATASET_SERVER_MAX_ATTEMPTS:
            sleeper(float(2**attempt))
    raise GateEError("Dataset Server request failed after bounded retries") from last_error


def _dataset_server_page(
    payload: Mapping[str, Any],
    *,
    offset: int,
    length: int,
    filtered: bool,
) -> tuple[dict[str, str], int, bool, list[Mapping[str, Any]], tuple[int, ...]]:
    schema = _server_schema(payload.get("features"))
    total_rows = payload.get("num_rows_total")
    partial = payload.get("partial")
    rows = payload.get("rows")
    if type(total_rows) is not int or total_rows <= 0:
        raise GateEError("Dataset Server total row count is invalid")
    if type(partial) is not bool:
        raise GateEError("Dataset Server partial flag is invalid")
    if not isinstance(rows, list) or len(rows) != length:
        raise GateEError("Dataset Server returned an underfilled row window")
    extracted: list[Mapping[str, Any]] = []
    row_indexes: list[int] = []
    for position, record in enumerate(rows):
        if not isinstance(record, Mapping):
            raise GateEError("Dataset Server row record is invalid")
        row_index = record.get("row_idx")
        if type(row_index) is not int or row_index < 0:
            raise GateEError("Dataset Server row index is invalid")
        if filtered:
            if row_indexes and row_index <= row_indexes[-1]:
                raise GateEError("Dataset Server filtered row indexes are not increasing")
        elif row_index != offset + position:
            raise GateEError("Dataset Server row indexes drifted from the requested window")
        if record.get("truncated_cells") != []:
            raise GateEError("Dataset Server truncated at least one selected row")
        row = record.get("row")
        if not isinstance(row, Mapping):
            raise GateEError("Dataset Server returned a non-object row")
        extracted.append(row)
        row_indexes.append(row_index)
    return schema, total_rows, partial, extracted, tuple(row_indexes)


def hf_dataset_server_loader(
    source: SourceSpec,
    cache_dir: Path,
    documents: int,
    *,
    opener: Callable[..., Any] = urlopen,
    sleeper: Callable[[float], None] = time.sleep,
) -> LoadedSource:
    """Fetch an exact, bounded, stratified row sample from the official Viewer API."""
    del cache_dir
    _ensure_revision(source.revision)
    if not 1 <= documents <= source.inspection_cap:
        raise GateEError("Dataset Server document request exceeds the source cap")

    probe_payload, probe_bytes, probe_attempts = _dataset_server_request(
        source,
        offset=0,
        length=1,
        opener=opener,
        sleeper=sleeper,
    )
    filtered = source.dataset_server_where is not None
    schema, total_rows, partial, probe_rows, probe_indexes = _dataset_server_page(
        probe_payload,
        offset=0,
        length=1,
        filtered=filtered,
    )
    windows = _stratified_windows(total_rows, documents)
    rows: list[Mapping[str, Any]] = list(probe_rows)
    response_bytes = probe_bytes
    request_count = probe_attempts
    previous_row_index = probe_indexes[-1]
    for offset, length in windows[1:]:
        payload, page_bytes, attempts = _dataset_server_request(
            source,
            offset=offset,
            length=length,
            opener=opener,
            sleeper=sleeper,
        )
        page_schema, page_total, page_partial, page_rows, page_indexes = _dataset_server_page(
            payload,
            offset=offset,
            length=length,
            filtered=filtered,
        )
        if page_schema != schema:
            raise GateEError("Dataset Server schema drifted between bounded windows")
        if page_total != total_rows or page_partial is not partial:
            raise GateEError("Dataset Server population metadata drifted between windows")
        if filtered and page_indexes[0] <= previous_row_index:
            raise GateEError("Dataset Server filtered row indexes drifted across windows")
        previous_row_index = page_indexes[-1]
        response_bytes += page_bytes
        request_count += attempts
        if response_bytes > DATASET_SERVER_MAX_TOTAL_BYTES:
            raise GateEError("Dataset Server responses exceed the total byte cap")
        rows.extend(page_rows)
    if len(rows) != documents:
        raise AssertionError("Dataset Server loader must return exactly the requested documents")
    return LoadedSource(
        rows=tuple(rows),
        resolved_revision=source.revision,
        live_schema=schema,
        transport=(
            "huggingface_dataset_server_filter" if filtered else "huggingface_dataset_server_rows"
        ),
        response_bytes=response_bytes,
        request_count=request_count,
        reported_rows=total_rows,
        partial=partial,
        sample_windows=windows,
    )


def hf_stream_loader(source: SourceSpec, cache_dir: Path, documents: int) -> LoadedSource:
    """Load an exact revision as an IterableDataset; imports stay lazy for CPU CI."""
    del documents
    _configure_hf_cache(cache_dir)
    try:
        from datasets import load_dataset
        from huggingface_hub import HfApi
    except ImportError as exc:  # pragma: no cover - exercised only in lean runtime envs
        raise GateEError("datasets and huggingface_hub are required for live Gate E") from exc

    info = HfApi().dataset_info(source.dataset, revision=source.revision)
    if info.sha != source.revision:
        raise GateEError("Hugging Face resolved revision does not match the pinned revision")
    dataset = load_dataset(
        source.dataset,
        source.dataset_config,
        split=source.split,
        revision=source.revision,
        streaming=True,
        cache_dir=str(cache_dir / "datasets"),
    )
    if dataset.features is None:
        raise GateEError("streaming dataset did not expose a live schema")
    live_schema = _flatten_features(dataset.features)
    return LoadedSource(
        rows=dataset,
        resolved_revision=info.sha,
        live_schema=live_schema,
        transport="huggingface_datasets_streaming",
    )


def _get_path(row: Mapping[str, Any], path: str) -> Any:
    current: Any = row
    for part in path.split("."):
        if not isinstance(current, Mapping) or part not in current:
            return None
        current = current[part]
    return current


def _schema_missing_or_mismatched(
    required: tuple[tuple[str, str], ...], live: Mapping[str, str]
) -> list[dict[str, str | None]]:
    mismatches = []
    for path, expected in required:
        observed = live.get(path)
        if observed != expected:
            mismatches.append({"field": path, "expected": expected, "observed": observed})
    return mismatches


def _path_is_vendor(path: str) -> bool:
    parts = {part for part in path.casefold().replace("\\", "/").split("/") if part}
    return bool(parts.intersection(_VENDOR_PARTS))


def _pathological_repetition(text: str) -> bool:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if len(lines) < 20:
        return False
    counts = Counter(lines)
    repeated_excess = sum(count - 1 for count in counts.values() if count > 1)
    return repeated_excess / len(lines) >= 0.30 or max(counts.values(), default=0) >= 5


def _numeric_quality(row: Mapping[str, Any], source: SourceSpec) -> float | None:
    if source.quality_field is None:
        return None
    value = _get_path(row, source.quality_field)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    numeric = float(value)
    return numeric if math.isfinite(numeric) else None


def _filter_row(
    row: Mapping[str, Any], source: SourceSpec
) -> tuple[
    str | None,
    bytes | None,
    float | None,
    tuple[str, ...],
    tuple[str, ...],
]:
    reasons: list[str] = []
    diagnostics: list[str] = []
    raw_text = _get_path(row, source.text_field)
    if raw_text is None:
        return None, None, _numeric_quality(row, source), ("missing_text",), ()
    if not isinstance(raw_text, str):
        return None, None, _numeric_quality(row, source), ("non_string_text",), ()
    try:
        encoded = raw_text.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        return raw_text, None, _numeric_quality(row, source), ("strict_utf8_failed",), ()
    if "\N{REPLACEMENT CHARACTER}" in raw_text:
        reasons.append("unicode_replacement_character")
    if not raw_text.strip():
        reasons.append("empty_or_whitespace")
    if len(encoded) < source.minimum_bytes:
        reasons.append("below_minimum_bytes")
    if len(encoded) > source.maximum_bytes:
        reasons.append("above_maximum_bytes")

    if source.language_field is not None:
        language = _get_path(row, source.language_field)
        if language != source.language_value:
            reasons.append("language_mismatch")

    quality = _numeric_quality(row, source)
    if source.quality_field is not None:
        raw_quality = _get_path(row, source.quality_field)
        if quality is None:
            reasons.append(
                "quality_missing" if raw_quality is None else "quality_non_numeric_or_nonfinite"
            )
        elif source.minimum_quality is not None and quality < source.minimum_quality:
            reasons.append("quality_below_minimum")

    if _pathological_repetition(raw_text):
        reasons.append("pathological_repetition")

    if source.python_gate:
        metadata = row.get("metadata")
        if not isinstance(metadata, Mapping):
            reasons.append("python_metadata_missing")
        else:
            if metadata.get("src_encoding") != "UTF-8":
                reasons.append("source_encoding_not_exact_utf8")
            reported_length = metadata.get("length_bytes")
            if not isinstance(reported_length, int) or isinstance(reported_length, bool):
                reasons.append("metadata_length_missing")
            elif reported_length != len(encoded):
                diagnostics.append("metadata_length_mismatch")
            if metadata.get("is_generated") is not False:
                reasons.append("generated_metadata")
            path = metadata.get("path")
            if metadata.get("is_vendor") is not False or (
                isinstance(path, str) and _path_is_vendor(path)
            ):
                reasons.append("vendor_metadata_or_path")
        lowered_prefix = raw_text[:4_096].casefold()
        if any(marker in lowered_prefix for marker in _GENERATED_MARKERS):
            reasons.append("generated_marker")
        try:
            ast.parse(raw_text)
        except (SyntaxError, ValueError, TypeError, MemoryError):
            reasons.append("python_ast_parse_failed")

    return (
        raw_text,
        encoded,
        quality,
        tuple(dict.fromkeys(reasons)),
        tuple(dict.fromkeys(diagnostics)),
    )


def _review_reasons(
    source: SourceSpec,
    *,
    encoded: bytes,
    quality: float | None,
    basic_reasons: tuple[str, ...],
) -> tuple[str, ...]:
    """Select transparent boundary examples without changing basic acceptance."""
    if basic_reasons:
        return basic_reasons
    reasons: list[str] = []
    if (
        source.review_minimum_quality is not None
        and quality is not None
        and quality < source.review_minimum_quality
    ):
        reasons.append("review_quality_below_boundary")
    if source.review_minimum_bytes is not None and len(encoded) < source.review_minimum_bytes:
        reasons.append("review_below_minimum_bytes")
    if source.review_maximum_bytes is not None and len(encoded) > source.review_maximum_bytes:
        reasons.append("review_above_maximum_bytes")
    return tuple(reasons)


def _quantiles(values: list[int | float]) -> dict[str, int | float | None]:
    if not values:
        return {
            "count": 0,
            "min": None,
            "p25": None,
            "p50": None,
            "p75": None,
            "p90": None,
            "p95": None,
            "p99": None,
            "max": None,
            "mean": None,
        }
    ordered = sorted(values)

    def nearest_rank(fraction: float) -> int | float:
        index = max(0, math.ceil(fraction * len(ordered)) - 1)
        return ordered[index]

    return {
        "count": len(ordered),
        "min": ordered[0],
        "p25": nearest_rank(0.25),
        "p50": nearest_rank(0.50),
        "p75": nearest_rank(0.75),
        "p90": nearest_rank(0.90),
        "p95": nearest_rank(0.95),
        "p99": nearest_rank(0.99),
        "max": ordered[-1],
        "mean": sum(ordered) / len(ordered),
    }


def _safe_snippet(text: str, limit: int) -> str:
    result: list[str] = []
    for character in text:
        category = unicodedata.category(character)
        if character in {"\n", "\t"}:
            rendered = character
        elif category.startswith("C") or category in {"Zl", "Zp"}:
            rendered = f"U+{ord(character):04X}"
        else:
            rendered = character
        if sum(len(part) for part in result) + len(rendered) > limit:
            break
        result.append(rendered)
    return "".join(result)


def _consider_snippet(
    reservoir: list[tuple[str, dict[str, Any]]],
    *,
    limit: int,
    source: SourceSpec,
    bucket: str,
    row_index: int,
    text: str,
    encoded: bytes,
    quality: float | None,
    reasons: tuple[str, ...],
    snippet_characters: int,
) -> None:
    rank = hashlib.sha256(
        f"{source.key}\0{bucket}\0{row_index}\0".encode("ascii") + hashlib.sha256(encoded).digest()
    ).hexdigest()
    record = {
        "bucket": bucket,
        "sample_index": row_index,
        "utf8_bytes": len(encoded),
        "quality_score": quality,
        "rejection_causes": list(reasons),
        "snippet": _safe_snippet(text, snippet_characters),
    }
    reservoir.append((rank, record))
    reservoir.sort(key=lambda item: item[0])
    del reservoir[limit:]


def _directory_allocated_bytes(path: Path) -> int:
    if not path.exists():
        return 0
    total = 0
    for item in path.rglob("*"):
        try:
            stat = item.stat(follow_symlinks=False)
        except FileNotFoundError:
            continue
        total += stat.st_blocks * 512
    return total


def _write_new_file(path: Path, content: bytes) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC, 0o600)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
    finally:
        os.close(descriptor)


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _publish_directory(staging: Path, destination: Path) -> None:
    _fsync_directory(staging)
    if destination.exists():
        raise GateEError(f"refusing to overwrite published output: {destination}")
    os.rename(staging, destination)
    _fsync_directory(destination.parent)


def _inspection_staging(output_dir: Path) -> Path:
    return output_dir.parent / f".{output_dir.name}.building-{uuid.uuid4().hex}"


def inspect_corpus(
    config: InspectionConfig,
    *,
    loader: SourceLoader = hf_dataset_server_loader,
    clock: Callable[[], float] = time.perf_counter,
) -> dict[str, Any]:
    """Inspect one source and atomically publish a report + short snippets."""
    output_dir = config.output_dir.resolve(strict=False)
    staging = _inspection_staging(output_dir)
    _validate_inspection_config(config, staging)
    cache_dir = config.cache_dir.resolve(strict=False)
    if output_dir.exists():
        raise GateEError(f"refusing to overwrite published inspection: {output_dir}")
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_before = _directory_allocated_bytes(cache_dir)
    started = clock()
    loaded = loader(config.source, cache_dir, config.documents)
    if loaded.resolved_revision != config.source.revision:
        raise GateEError("resolved source revision drifted from the pinned revision")
    live_schema = dict(sorted(loaded.live_schema.items()))
    schema_mismatches = _schema_missing_or_mismatched(config.source.required_schema, live_schema)
    if schema_mismatches:
        raise GateEError(f"live schema mismatch: {schema_mismatches}")

    lengths_characters: list[int] = []
    lengths_bytes: list[int] = []
    quality_scores: list[float] = []
    rejection_causes: Counter[str] = Counter()
    diagnostic_counts: Counter[str] = Counter()
    review_rejection_causes: Counter[str] = Counter()
    accepted_count = 0
    rejected_count = 0
    strict_utf8_success = 0
    accepted_bytes = 0
    accepted_snippets: list[tuple[str, dict[str, Any]]] = []
    rejected_snippets: list[tuple[str, dict[str, Any]]] = []
    inspected = 0

    iterator = iter(loaded.rows)
    for row_index in range(config.documents):
        if clock() - started > config.max_wall_seconds:
            raise GateEError("bounded inspection exceeded max_wall_seconds")
        try:
            row = next(iterator)
        except StopIteration:
            break
        if not isinstance(row, Mapping):
            raise GateEError("stream yielded a non-object row")
        inspected += 1
        text, encoded, quality, reasons, diagnostics = _filter_row(row, config.source)
        if text is not None:
            lengths_characters.append(len(text))
        strict_utf8_ok = encoded is not None and not {
            "strict_utf8_failed",
            "unicode_replacement_character",
            "source_encoding_not_exact_utf8",
        }.intersection(reasons)
        if encoded is not None:
            lengths_bytes.append(len(encoded))
        if strict_utf8_ok:
            strict_utf8_success += 1
        if quality is not None:
            quality_scores.append(quality)
        diagnostic_counts.update(diagnostics)

        if not reasons:
            if text is None or encoded is None:
                raise AssertionError("accepted row must contain strict UTF-8 text")
            accepted_count += 1
            accepted_bytes += len(encoded)
        else:
            rejected_count += 1
            rejection_causes.update(reasons)

        if text is not None and encoded is not None:
            frame_reasons = _review_reasons(
                config.source,
                encoded=encoded,
                quality=quality,
                basic_reasons=reasons,
            )
            if frame_reasons:
                review_rejection_causes.update(frame_reasons)
                _consider_snippet(
                    rejected_snippets,
                    limit=config.rejected_snippets,
                    source=config.source,
                    bucket="rejected",
                    row_index=row_index,
                    text=text,
                    encoded=encoded,
                    quality=quality,
                    reasons=frame_reasons,
                    snippet_characters=config.snippet_characters,
                )
            else:
                _consider_snippet(
                    accepted_snippets,
                    limit=config.accepted_snippets,
                    source=config.source,
                    bucket="accepted",
                    row_index=row_index,
                    text=text,
                    encoded=encoded,
                    quality=quality,
                    reasons=(),
                    snippet_characters=config.snippet_characters,
                )

    elapsed = clock() - started
    if inspected != config.documents:
        raise GateEError(
            f"source exhausted after {inspected} rows; expected exactly {config.documents}"
        )
    if elapsed <= 0:
        raise GateEError("inspection clock did not advance")

    snippets = [record for _, record in accepted_snippets] + [
        record for _, record in rejected_snippets
    ]
    snippet_bytes = b"".join(_canonical_json_bytes(record) + b"\n" for record in snippets)
    snippet_sha256 = _sha256_bytes(snippet_bytes)
    cache_after = _directory_allocated_bytes(cache_dir)
    pass_criteria = {
        "exact_revision": loaded.resolved_revision == config.source.revision,
        "required_schema": not schema_mismatches,
        "requested_rows_inspected": inspected == config.documents,
        "strict_utf8_success_rate_at_least_99_percent": strict_utf8_success / inspected >= 0.99,
        "at_least_20_accepted_documents": accepted_count >= MIN_ACCEPTED_FOR_GATE_E,
        "accepted_review_snippets_complete": len(accepted_snippets) == config.accepted_snippets,
        "rejected_review_snippets_complete": len(rejected_snippets) == config.rejected_snippets,
    }
    gate_status = "PASS" if all(pass_criteria.values()) else "BLOCKED"
    accepted_rate = accepted_count / inspected
    estimated_usable_documents = (
        int(config.source.volume_rows * accepted_rate)
        if config.source.volume_rows is not None
        else None
    )
    estimated_usable_utf8_bytes = (
        int(config.source.volume_rows * accepted_bytes / inspected)
        if config.source.volume_rows is not None
        else None
    )
    report: dict[str, Any] = {
        "schema_version": TOOL_SCHEMA_VERSION,
        "generated_at_utc": _utc_now(),
        "git_head": _git_head(),
        "source": {
            "key": config.source.key,
            "dataset": config.source.dataset,
            "config": config.source.dataset_config,
            "split": config.source.split,
            "revision": config.source.revision,
            "card_license_fact": config.source.card_license_fact,
            "license_fact_used_as_quality_score": False,
        },
        "access": {
            "transport": loaded.transport,
            "resolved_revision": loaded.resolved_revision,
            "success": True,
            "documents_requested": config.documents,
            "documents_inspected": inspected,
            "strict_utf8_success": strict_utf8_success,
            "strict_utf8_failed": inspected - strict_utf8_success,
            "max_documents_contract": config.source.inspection_cap,
            "cache_allocated_growth_bytes": max(0, cache_after - cache_before),
            "dataset_server_response_bytes": loaded.response_bytes,
            "dataset_server_request_count": loaded.request_count,
            "dataset_server_reported_rows": loaded.reported_rows,
            "dataset_server_partial": loaded.partial,
            "sample_windows": [
                {"offset": offset, "length": length} for offset, length in loaded.sample_windows
            ],
            "transport_bounds": {
                "max_windows": DATASET_SERVER_MAX_WINDOWS,
                "max_response_bytes": DATASET_SERVER_MAX_RESPONSE_BYTES,
                "max_total_bytes": DATASET_SERVER_MAX_TOTAL_BYTES,
                "timeout_seconds": DATASET_SERVER_TIMEOUT_SECONDS,
                "max_attempts_per_request": DATASET_SERVER_MAX_ATTEMPTS,
            },
        },
        "live_schema": live_schema,
        "length_summary": {
            "characters": _quantiles(lengths_characters),
            "utf8_bytes": _quantiles(lengths_bytes),
        },
        "quality_score": {
            "field": config.source.quality_field,
            "minimum_for_basic_filter": config.source.minimum_quality,
            "summary": _quantiles(quality_scores),
        },
        "basic_filter": {
            "version": FILTER_VERSION,
            "minimum_bytes": config.source.minimum_bytes,
            "maximum_bytes": config.source.maximum_bytes,
            "python_gate": config.source.python_gate,
            "accepted": accepted_count,
            "rejected": rejected_count,
            "acceptance_rate": accepted_rate,
            "common_rejection_causes": dict(rejection_causes.most_common()),
            "diagnostic_counts_not_used_as_rejections": dict(diagnostic_counts.most_common()),
        },
        "review_artifact": {
            "selection": {
                "scope": config.source.review_scope,
                "basic_rejections_always_in_rejected_bucket": True,
                "review_minimum_quality": config.source.review_minimum_quality,
                "review_minimum_bytes": config.source.review_minimum_bytes,
                "review_maximum_bytes": config.source.review_maximum_bytes,
                "rejection_causes": dict(review_rejection_causes.most_common()),
                "changes_basic_filter_accounting": False,
            },
            "filename": "review_snippets.jsonl",
            "sha256": snippet_sha256,
            "accepted_requested": config.accepted_snippets,
            "accepted_written": len(accepted_snippets),
            "rejected_requested": config.rejected_snippets,
            "rejected_written": len(rejected_snippets),
            "accepted_shortfall": max(0, config.accepted_snippets - len(accepted_snippets)),
            "rejected_shortfall": max(0, config.rejected_snippets - len(rejected_snippets)),
            "snippet_characters": config.snippet_characters,
        },
        "rough_usable_volume": {
            "basis_rows": config.source.volume_rows,
            "basis": config.source.volume_rows_basis,
            "estimated_usable_documents_point": estimated_usable_documents,
            "estimated_usable_utf8_bytes_point": estimated_usable_utf8_bytes,
            "warning": "bounded sample point estimate only; not a final quota or token estimate",
        },
        "throughput": {
            "elapsed_seconds": elapsed,
            "documents_per_second": inspected / elapsed,
            "decoded_mib_per_second": sum(lengths_bytes) / elapsed / (1024 * 1024),
        },
        "gate_e": {
            "status": gate_status,
            "criteria": pass_criteria,
            "scope": "bounded source feasibility only; Gate C and Gate R remain required",
        },
    }

    try:
        staging.mkdir(mode=0o700)
        _write_new_file(staging / "review_snippets.jsonl", snippet_bytes)
        _write_new_file(staging / "report.json", _canonical_json_bytes(report) + b"\n")
        _publish_directory(staging, output_dir)
    except BaseException:
        if staging.exists():
            shutil.rmtree(staging)
        raise
    return report


def _read_regular_bytes(path: Path) -> bytes:
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise GateEError(f"cannot open regular artifact: {path.name}") from exc
    try:
        file_stat = os.fstat(descriptor)
        if not stat.S_ISREG(file_stat.st_mode):
            raise GateEError(f"artifact is not a regular file: {path.name}")
        with os.fdopen(descriptor, "rb", closefd=False) as handle:
            return handle.read()
    finally:
        os.close(descriptor)


def _load_json_object(path: Path) -> tuple[dict[str, Any], str]:
    raw = _read_regular_bytes(path)
    try:
        value = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise GateEError(f"invalid JSON artifact: {path.name}") from exc
    if not isinstance(value, dict):
        raise GateEError(f"JSON artifact is not an object: {path.name}")
    return value, _sha256_bytes(raw)


_GATE_E_CRITERIA = frozenset({
    "exact_revision",
    "required_schema",
    "requested_rows_inspected",
    "strict_utf8_success_rate_at_least_99_percent",
    "at_least_20_accepted_documents",
    "accepted_review_snippets_complete",
    "rejected_review_snippets_complete",
})


def _validate_review_artifact(report_path: Path, review: Mapping[str, Any]) -> None:
    if review.get("filename") != "review_snippets.jsonl":
        raise GateEError("inspection report review filename is invalid")
    accepted_requested = review.get("accepted_requested")
    rejected_requested = review.get("rejected_requested")
    if type(accepted_requested) is not int or not 20 <= accepted_requested <= 30:
        raise GateEError("inspection accepted review request is invalid")
    if type(rejected_requested) is not int or not 10 <= rejected_requested <= 15:
        raise GateEError("inspection rejected review request is invalid")
    if (
        review.get("accepted_written") != accepted_requested
        or review.get("rejected_written") != rejected_requested
    ):
        raise GateEError("inspection review artifact is incomplete")
    if review.get("accepted_shortfall") != 0 or review.get("rejected_shortfall") != 0:
        raise GateEError("inspection review artifact reports a shortfall")
    review_path = report_path.with_name("review_snippets.jsonl")
    raw = _read_regular_bytes(review_path)
    if review.get("sha256") != _sha256_bytes(raw):
        raise GateEError("inspection review artifact SHA-256 mismatch")
    rows: list[dict[str, Any]] = []
    for line in raw.splitlines():
        try:
            row = json.loads(line)
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise GateEError("inspection review artifact contains invalid JSONL") from exc
        if not isinstance(row, dict):
            raise GateEError("inspection review artifact row is not an object")
        rows.append(row)
    accepted_rows = [row for row in rows if row.get("bucket") == "accepted"]
    rejected_rows = [row for row in rows if row.get("bucket") == "rejected"]
    if len(rows) != accepted_requested + rejected_requested:
        raise GateEError("inspection review artifact row count mismatch")
    if len(accepted_rows) != accepted_requested or len(rejected_rows) != rejected_requested:
        raise GateEError("inspection review artifact bucket count mismatch")
    if any(row.get("rejection_causes") != [] for row in accepted_rows):
        raise GateEError("accepted review row contains rejection causes")
    if any(not row.get("rejection_causes") for row in rejected_rows):
        raise GateEError("rejected review row is missing rejection causes")
    if any(not isinstance(row.get("snippet"), str) for row in rows):
        raise GateEError("inspection review row has invalid snippet text")


def _validate_passing_inspection(path: Path, source: SourceSpec) -> str:
    if path.name != "report.json":
        raise GateEError("candidate smoke requires the exact Gate E report.json")
    report, report_sha256 = _load_json_object(path)
    if report.get("schema_version") != TOOL_SCHEMA_VERSION:
        raise GateEError("inspection report schema version is not current")
    source_record = report.get("source")
    access = report.get("access")
    live_schema = report.get("live_schema")
    basic_filter = report.get("basic_filter")
    review = report.get("review_artifact")
    gate = report.get("gate_e")
    if not all(
        isinstance(value, Mapping)
        for value in (source_record, access, live_schema, basic_filter, review, gate)
    ):
        raise GateEError("inspection report is missing required records")
    expected_source = {
        "key": source.key,
        "dataset": source.dataset,
        "config": source.dataset_config,
        "split": source.split,
        "revision": source.revision,
    }
    for key, value in expected_source.items():
        if source_record.get(key) != value:
            raise GateEError("inspection report source identity does not match smoke source")
    if access.get("resolved_revision") != source.revision:
        raise GateEError("inspection report did not resolve the pinned revision")
    if (
        access.get("documents_requested") != source.inspection_cap
        or access.get("documents_inspected") != source.inspection_cap
    ):
        raise GateEError("inspection report did not complete the frozen source cap")
    schema_mismatches = _schema_missing_or_mismatched(source.required_schema, live_schema)
    if schema_mismatches:
        raise GateEError("inspection report live schema does not match the source contract")
    if basic_filter.get("version") != FILTER_VERSION:
        raise GateEError("inspection report basic filter version is not current")
    criteria = gate.get("criteria")
    if not isinstance(criteria, Mapping) or frozenset(criteria) != _GATE_E_CRITERIA:
        raise GateEError("inspection report Gate E criteria are incomplete")
    if any(value is not True for value in criteria.values()) or gate.get("status") != "PASS":
        raise GateEError("candidate smoke requires every Gate E criterion to pass")
    _validate_review_artifact(path, review)
    return report_sha256


def _smoke_fingerprint(config: SmokeConfig, report_sha256: str) -> str:
    return _sha256_bytes(
        _canonical_json_bytes({
            "schema_version": TOOL_SCHEMA_VERSION,
            "filter_version": FILTER_VERSION,
            "source": {
                "key": config.source.key,
                "dataset": config.source.dataset,
                "config": config.source.dataset_config,
                "split": config.source.split,
                "revision": config.source.revision,
            },
            "inspection_report_sha256": report_sha256,
            "target_documents": config.target_documents,
            "max_scanned": config.max_scanned,
        })
    )


def _atomic_replace_json(path: Path, value: Mapping[str, Any]) -> None:
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        _write_new_file(temporary, _canonical_json_bytes(value) + b"\n")
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        if temporary.exists():
            temporary.unlink()


def _checkpoint_smoke(
    *,
    partial_path: Path,
    state_path: Path,
    state: dict[str, Any],
) -> None:
    with partial_path.open("ab") as handle:
        handle.flush()
        os.fsync(handle.fileno())
    raw = _read_regular_bytes(partial_path)
    state["committed_output_bytes"] = len(raw)
    state["committed_output_sha256"] = _sha256_bytes(raw)
    _atomic_replace_json(state_path, state)


def _new_smoke_state(fingerprint: str) -> dict[str, Any]:
    return {
        "schema_version": TOOL_SCHEMA_VERSION,
        "fingerprint": fingerprint,
        "next_row_index": 0,
        "accepted": 0,
        "rejected": 0,
        "rejection_causes": {},
        "resume_count": 0,
        "committed_output_bytes": 0,
        "committed_output_sha256": _sha256_bytes(b""),
    }


def _require_nonnegative_int(value: Any, label: str) -> int:
    if type(value) is not int or value < 0:
        raise GateEError(f"candidate smoke checkpoint {label} is invalid")
    return value


def _validate_candidate_records(raw: bytes, source: SourceSpec, expected_count: int) -> None:
    lines = raw.splitlines()
    if len(lines) != expected_count:
        raise GateEError("candidate smoke committed line count mismatch")
    previous_index = -1
    for line in lines:
        try:
            row = json.loads(line)
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise GateEError("candidate smoke committed JSONL is invalid") from exc
        if not isinstance(row, dict) or not isinstance(row.get("text"), str):
            raise GateEError("candidate smoke committed row is invalid")
        metadata = row.get("_petitgpt_candidate")
        if not isinstance(metadata, Mapping):
            raise GateEError("candidate smoke committed provenance is missing")
        expected_identity = {
            "source_key": source.key,
            "dataset": source.dataset,
            "config": source.dataset_config,
            "split": source.split,
            "revision": source.revision,
            "transform": "identity",
            "smoke_only": True,
        }
        if any(metadata.get(key) != value for key, value in expected_identity.items()):
            raise GateEError("candidate smoke committed provenance drifted")
        row_index = metadata.get("source_row_index")
        if type(row_index) is not int or row_index <= previous_index:
            raise GateEError("candidate smoke source row order is invalid")
        previous_index = row_index
        text_bytes = row["text"].encode("utf-8", errors="strict")
        if metadata.get("text_sha256") != _sha256_bytes(text_bytes):
            raise GateEError("candidate smoke text SHA-256 mismatch")


def _load_or_create_smoke_state(
    *,
    staging: Path,
    fingerprint: str,
    source: SourceSpec,
    config: SmokeConfig,
) -> tuple[dict[str, Any] | None, Path | None, Path, bool]:
    partial_path = staging / "candidate.jsonl.partial"
    final_path = staging / "candidate.jsonl"
    state_path = staging / "state.json"
    manifest_path = staging / "manifest.json"
    if not staging.exists():
        try:
            staging.mkdir(mode=0o700)
            _write_new_file(partial_path, b"")
            state = _new_smoke_state(fingerprint)
            _atomic_replace_json(state_path, state)
        except BaseException:
            if staging.exists():
                shutil.rmtree(staging)
            raise
        return state, partial_path, state_path, True
    if not staging.is_dir():
        raise GateEError("candidate smoke staging path is not a directory")
    entries = {path.name for path in staging.iterdir()}
    allowed = {partial_path.name, final_path.name, state_path.name, manifest_path.name}
    if not entries.issubset(allowed):
        raise GateEError("candidate smoke staging has unexpected entries")
    if not state_path.exists():
        if entries != {final_path.name, manifest_path.name}:
            raise GateEError("candidate smoke finalizing state is incomplete")
        return None, final_path, state_path, False
    if (partial_path.exists()) == (final_path.exists()):
        raise GateEError("candidate smoke staging must contain exactly one data file")
    data_path = partial_path if partial_path.exists() else final_path
    if manifest_path.exists() and data_path != final_path:
        raise GateEError("candidate smoke manifest appeared before final data")
    state, _ = _load_json_object(state_path)
    if state.get("schema_version") != TOOL_SCHEMA_VERSION:
        raise GateEError("candidate smoke checkpoint schema version mismatch")
    if state.get("fingerprint") != fingerprint:
        raise GateEError("candidate smoke checkpoint fingerprint mismatch")
    next_row = _require_nonnegative_int(state.get("next_row_index"), "next row")
    accepted = _require_nonnegative_int(state.get("accepted"), "accepted count")
    rejected = _require_nonnegative_int(state.get("rejected"), "rejected count")
    _require_nonnegative_int(state.get("resume_count"), "resume count")
    if next_row != accepted + rejected or next_row > config.max_scanned:
        raise GateEError("candidate smoke checkpoint accounting mismatch")
    if accepted > config.target_documents:
        raise GateEError("candidate smoke checkpoint exceeded its target")
    raw_causes = state.get("rejection_causes")
    if not isinstance(raw_causes, Mapping):
        raise GateEError("candidate smoke checkpoint rejection causes are invalid")
    cause_total = sum(
        _require_nonnegative_int(value, "rejection cause") for value in raw_causes.values()
    )
    if cause_total < rejected:
        raise GateEError("candidate smoke checkpoint rejection causes undercount")
    expected_bytes = _require_nonnegative_int(state.get("committed_output_bytes"), "byte offset")
    expected_sha256 = state.get("committed_output_sha256")
    if not isinstance(expected_sha256, str) or not re.fullmatch(r"[0-9a-f]{64}", expected_sha256):
        raise GateEError("candidate smoke checkpoint SHA-256 is invalid")
    raw = _read_regular_bytes(data_path)
    if len(raw) < expected_bytes:
        raise GateEError("candidate smoke data is shorter than its checkpoint")
    committed = raw[:expected_bytes]
    if _sha256_bytes(committed) != expected_sha256:
        raise GateEError("candidate smoke data does not match its checkpoint")
    if data_path == final_path and len(raw) != expected_bytes:
        raise GateEError("candidate smoke final data has uncommitted bytes")
    _validate_candidate_records(committed, source, accepted)
    return state, data_path, state_path, False


def _make_smoke_manifest(
    *,
    config: SmokeConfig,
    report_sha256: str,
    fingerprint: str,
    state: Mapping[str, Any],
    output_bytes: bytes,
    generated_at_utc: str,
    git_head: str,
) -> dict[str, Any]:
    accepted = int(state["accepted"])
    rejected = int(state["rejected"])
    return {
        "schema_version": "petitgpt-candidate-smoke-manifest-v1",
        "generated_at_utc": generated_at_utc,
        "git_head": git_head,
        "status": "SMOKE_PASS",
        "scope": "mechanical smoke only; not a production candidate quota",
        "source": {
            "key": config.source.key,
            "dataset": config.source.dataset,
            "config": config.source.dataset_config,
            "split": config.source.split,
            "revision": config.source.revision,
        },
        "inspection_report_sha256": report_sha256,
        "config_fingerprint": fingerprint,
        "accounting": {
            "rows_scanned": int(state["next_row_index"]),
            "accepted": accepted,
            "rejected": rejected,
            "rejection_causes": dict(
                Counter({
                    str(key): int(value)
                    for key, value in dict(state.get("rejection_causes", {})).items()
                }).most_common()
            ),
            "target_documents": config.target_documents,
            "max_scanned": config.max_scanned,
            "resume_count": int(state["resume_count"]),
            "stop_reason": "target_documents",
        },
        "output": {
            "filename": "candidate.jsonl",
            "documents": accepted,
            "bytes": len(output_bytes),
            "sha256": _sha256_bytes(output_bytes),
        },
        "production_actions": {
            "bulk_candidate_quota_started": False,
            "tokenizer_trained": False,
            "final_shards_built": False,
            "model_training_started": False,
        },
    }


def _validate_published_smoke(
    directory: Path,
    *,
    config: SmokeConfig,
    report_sha256: str,
    fingerprint: str,
    allow_state: bool = False,
) -> dict[str, Any]:
    expected_entries = {"candidate.jsonl", "manifest.json"}
    if allow_state:
        expected_entries.add("state.json")
    if not directory.is_dir() or {path.name for path in directory.iterdir()} != expected_entries:
        raise GateEError("candidate smoke published/finalizing file set is invalid")
    data = _read_regular_bytes(directory / "candidate.jsonl")
    manifest, _ = _load_json_object(directory / "manifest.json")
    generated_at = manifest.get("generated_at_utc")
    manifest_git_head = manifest.get("git_head")
    if not isinstance(generated_at, str):
        raise GateEError("candidate smoke manifest timestamp is invalid")
    if not isinstance(manifest_git_head, str) or not re.fullmatch(
        r"[0-9a-f]{40}", manifest_git_head
    ):
        raise GateEError("candidate smoke manifest git HEAD is invalid")
    accounting = manifest.get("accounting")
    if not isinstance(accounting, Mapping):
        raise GateEError("candidate smoke manifest accounting is missing")
    accepted = _require_nonnegative_int(accounting.get("accepted"), "manifest accepted")
    rejected = _require_nonnegative_int(accounting.get("rejected"), "manifest rejected")
    next_row = _require_nonnegative_int(accounting.get("rows_scanned"), "manifest rows")
    resume_count = _require_nonnegative_int(accounting.get("resume_count"), "manifest resume count")
    if accepted != config.target_documents or next_row != accepted + rejected:
        raise GateEError("candidate smoke manifest accounting mismatch")
    state = {
        "next_row_index": next_row,
        "accepted": accepted,
        "rejected": rejected,
        "rejection_causes": accounting.get("rejection_causes"),
        "resume_count": resume_count,
    }
    expected = _make_smoke_manifest(
        config=config,
        report_sha256=report_sha256,
        fingerprint=fingerprint,
        state=state,
        output_bytes=data,
        generated_at_utc=generated_at,
        git_head=manifest_git_head,
    )
    if manifest != expected:
        raise GateEError("candidate smoke manifest does not match its bytes/config")
    _validate_candidate_records(data, config.source, accepted)
    return manifest


def build_candidate_smoke(
    config: SmokeConfig,
    *,
    loader: SourceLoader = hf_dataset_server_loader,
    clock: Callable[[], float] = time.perf_counter,
) -> dict[str, Any]:
    """Build a tiny restartable candidate release; never a production quota."""
    output_dir = config.output_dir.resolve(strict=False)
    staging = output_dir.parent / f".{output_dir.name}.building"
    _validate_smoke_config(config, staging)
    report_sha256 = _validate_passing_inspection(config.inspection_report, config.source)
    fingerprint = _smoke_fingerprint(config, report_sha256)
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    if output_dir.exists():
        if staging.exists():
            raise GateEError("published candidate and staging directory both exist")
        try:
            return _validate_published_smoke(
                output_dir,
                config=config,
                report_sha256=report_sha256,
                fingerprint=fingerprint,
            )
        except GateEError as exc:
            raise GateEError(
                "refusing to overwrite an unverified existing candidate smoke"
            ) from exc

    loaded = loader(config.source, config.cache_dir.resolve(strict=False), config.max_scanned)
    if loaded.resolved_revision != config.source.revision:
        raise GateEError("candidate smoke resolved revision drifted")
    schema_mismatches = _schema_missing_or_mismatched(
        config.source.required_schema, loaded.live_schema
    )
    if schema_mismatches:
        raise GateEError(f"candidate smoke live schema mismatch: {schema_mismatches}")

    state, data_path, state_path, created = _load_or_create_smoke_state(
        staging=staging,
        fingerprint=fingerprint,
        source=config.source,
        config=config,
    )
    if state is None:
        manifest = _validate_published_smoke(
            staging,
            config=config,
            report_sha256=report_sha256,
            fingerprint=fingerprint,
        )
        _publish_directory(staging, output_dir)
        return manifest
    if (staging / "manifest.json").exists():
        manifest = _validate_published_smoke(
            staging,
            config=config,
            report_sha256=report_sha256,
            fingerprint=fingerprint,
            allow_state=True,
        )
        state_path.unlink()
        _fsync_directory(staging)
        _publish_directory(staging, output_dir)
        return manifest
    if data_path is None:
        raise AssertionError("active candidate smoke requires a data path")

    committed_bytes = int(state["committed_output_bytes"])
    current_bytes = _read_regular_bytes(data_path)
    if len(current_bytes) > committed_bytes:
        if data_path.name != "candidate.jsonl.partial":
            raise GateEError("candidate smoke final data has an uncommitted tail")
        with data_path.open("r+b") as handle:
            handle.truncate(committed_bytes)
            handle.flush()
            os.fsync(handle.fileno())
    if not created:
        state["resume_count"] = int(state["resume_count"]) + 1
        _atomic_replace_json(state_path, state)

    started = clock()
    next_row_index = int(state["next_row_index"])
    accepted = int(state["accepted"])
    rejected = int(state["rejected"])
    rejection_causes = Counter({
        str(key): int(value) for key, value in dict(state.get("rejection_causes", {})).items()
    })
    if accepted < config.target_documents:
        iterator = iter(loaded.rows)
        exhausted = False
        for row_index in range(config.max_scanned):
            if clock() - started > config.max_wall_seconds:
                raise GateEError("candidate smoke exceeded max_wall_seconds")
            try:
                row = next(iterator)
            except StopIteration:
                exhausted = True
                break
            if row_index < next_row_index:
                continue
            if not isinstance(row, Mapping):
                raise GateEError("candidate smoke stream yielded a non-object row")
            text, encoded, _, reasons, _ = _filter_row(row, config.source)
            if not reasons:
                if text is None or encoded is None:
                    raise AssertionError("accepted smoke row must contain strict UTF-8 text")
                record = {
                    "text": text,
                    "_petitgpt_candidate": {
                        "schema_version": "petitgpt-candidate-smoke-v1",
                        "source_key": config.source.key,
                        "dataset": config.source.dataset,
                        "config": config.source.dataset_config,
                        "split": config.source.split,
                        "revision": config.source.revision,
                        "source_row_index": row_index,
                        "text_sha256": _sha256_bytes(encoded),
                        "transform": "identity",
                        "smoke_only": True,
                    },
                }
                with data_path.open("ab") as handle:
                    handle.write(_canonical_json_bytes(record) + b"\n")
                    handle.flush()
                    os.fsync(handle.fileno())
                accepted += 1
            else:
                rejected += 1
                rejection_causes.update(reasons)
            state.update({
                "next_row_index": row_index + 1,
                "accepted": accepted,
                "rejected": rejected,
                "rejection_causes": dict(rejection_causes),
            })
            _checkpoint_smoke(partial_path=data_path, state_path=state_path, state=state)
            if config.stop_after_documents is not None and accepted >= config.stop_after_documents:
                raise PlannedInterruption(
                    "planned candidate smoke interruption after durable checkpoint"
                )
            if accepted >= config.target_documents:
                break
        if accepted < config.target_documents:
            stop_reason = "stream_exhausted" if exhausted else "max_scanned"
            raise GateEError(
                f"candidate smoke underfilled: {accepted}/{config.target_documents} ({stop_reason})"
            )

    final_data = staging / "candidate.jsonl"
    if data_path != final_data:
        os.replace(data_path, final_data)
        _fsync_directory(staging)
    output_bytes = _read_regular_bytes(final_data)
    _validate_candidate_records(output_bytes, config.source, accepted)
    manifest = _make_smoke_manifest(
        config=config,
        report_sha256=report_sha256,
        fingerprint=fingerprint,
        state=state,
        output_bytes=output_bytes,
        generated_at_utc=_utc_now(),
        git_head=_git_head(),
    )
    _write_new_file(staging / "manifest.json", _canonical_json_bytes(manifest) + b"\n")
    state_path.unlink()
    _fsync_directory(staging)
    _publish_directory(staging, output_dir)
    return manifest


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser("inspect", help="run one bounded Gate E scan")
    inspect_parser.add_argument("--source", choices=sorted(SOURCE_SPECS), required=True)
    inspect_parser.add_argument("--output-dir", type=Path, required=True)
    inspect_parser.add_argument("--cache-dir", type=Path, required=True)
    inspect_parser.add_argument("--documents", type=int)
    inspect_parser.add_argument("--accepted-snippets", type=int, default=25)
    inspect_parser.add_argument("--rejected-snippets", type=int, default=12)
    inspect_parser.add_argument("--snippet-characters", type=int, default=400)
    inspect_parser.add_argument("--max-wall-seconds", type=float, default=1_800.0)

    smoke_parser = subparsers.add_parser(
        "candidate-smoke", help="prove tiny checkpoint/resume/atomic candidate mechanics"
    )
    smoke_parser.add_argument("--source", choices=sorted(SOURCE_SPECS), required=True)
    smoke_parser.add_argument("--inspection-report", type=Path, required=True)
    smoke_parser.add_argument("--output-dir", type=Path, required=True)
    smoke_parser.add_argument("--cache-dir", type=Path, required=True)
    smoke_parser.add_argument("--target-documents", type=int, default=8)
    smoke_parser.add_argument("--max-scanned", type=int, default=100)
    smoke_parser.add_argument("--stop-after-documents", type=int)
    smoke_parser.add_argument("--max-wall-seconds", type=float, default=1_800.0)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        source = SOURCE_SPECS[args.source]
        if args.command == "inspect":
            documents = args.documents if args.documents is not None else source.inspection_cap
            report = inspect_corpus(
                InspectionConfig(
                    source=source,
                    output_dir=args.output_dir,
                    cache_dir=args.cache_dir,
                    documents=documents,
                    accepted_snippets=args.accepted_snippets,
                    rejected_snippets=args.rejected_snippets,
                    snippet_characters=args.snippet_characters,
                    max_wall_seconds=args.max_wall_seconds,
                )
            )
            print(
                json.dumps(
                    {
                        "gate_e": report["gate_e"]["status"],
                        "report": str(args.output_dir / "report.json"),
                        "source": source.key,
                    },
                    sort_keys=True,
                )
            )
            return 0 if report["gate_e"]["status"] == "PASS" else 2

        manifest = build_candidate_smoke(
            SmokeConfig(
                source=source,
                inspection_report=args.inspection_report,
                output_dir=args.output_dir,
                cache_dir=args.cache_dir,
                target_documents=args.target_documents,
                max_scanned=args.max_scanned,
                stop_after_documents=args.stop_after_documents,
                max_wall_seconds=args.max_wall_seconds,
            )
        )
        print(
            json.dumps(
                {
                    "manifest": str(args.output_dir / "manifest.json"),
                    "source": source.key,
                    "status": manifest["status"],
                },
                sort_keys=True,
            )
        )
        return 0
    except PlannedInterruption:
        print("candidate smoke stopped after a durable planned checkpoint", file=sys.stderr)
        return 75
    except (GateEError, OSError, subprocess.SubprocessError) as exc:
        print(f"Gate E failed closed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
