#!/usr/bin/env python3

"""Run a bounded, revision-pinned inspection of SmolLM ``python-edu``.

This is deliberately an inspection tool, not a corpus downloader.  It samples
small deterministic windows across the metadata table, fetches a bounded subset
of Software Heritage blobs, and writes an auditable report without materializing
the full dataset.
"""

from __future__ import annotations

import argparse
import ast
from collections import Counter
from collections.abc import Callable, Mapping, Sequence
from dataclasses import asdict, dataclass
import hashlib
import io
import json
import math
import os
from pathlib import Path
import re
import sys
import time
import tokenize
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pretrain.data_preparation_tools.extract_smollm_python_edu import (  # noqa: E402
    decode_blob_bytes,
    fetch_blob_cached,
    make_software_heritage_fetcher,
)

DEFAULT_DATASET = "HuggingFaceTB/smollm-corpus"
DEFAULT_CONFIG = "python-edu"
DEFAULT_SPLIT = "train"
DEFAULT_API_ROOT = "https://datasets-server.huggingface.co"
MAX_METADATA_ROWS = 10_000
MAX_CONTENT_BLOBS = 1_000
MAX_WINDOW_SIZE = 100
MAX_HTTP_ATTEMPTS = 10
MAX_HTTP_BACKOFF_SECONDS = 60.0
_TRANSIENT_HTTP_STATUSES = frozenset({429, 500, 502, 503, 504})
_REVISION_RE = re.compile(r"[0-9a-f]{40}")
_REQUIRED_FIELDS = {
    "blob_id",
    "repo_name",
    "path",
    "length_bytes",
    "score",
    "int_score",
}
_VENDOR_PATH_PARTS = {
    "3rdparty",
    "deps",
    "external",
    "node_modules",
    "site-packages",
    "third_party",
    "thirdparty",
    "vendor",
    "vendored",
}
_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "generated by",
    "generated file",
)


@dataclass(frozen=True)
class HttpJsonResponse:
    payload: Mapping[str, Any]
    headers: Mapping[str, str]
    body_sha256: str
    http_status: int
    body_bytes: int
    request_latency_seconds: float


@dataclass(frozen=True)
class Window:
    stratum: int
    offset: int
    length: int


@dataclass(frozen=True)
class InspectionConfig:
    expected_revision: str
    report_path: Path
    examples_path: Path
    cache_dir: Path | None
    dataset: str = DEFAULT_DATASET
    dataset_config: str = DEFAULT_CONFIG
    split: str = DEFAULT_SPLIT
    api_root: str = DEFAULT_API_ROOT
    metadata_rows: int = 25
    window_size: int = 5
    content_blobs: int = 8
    max_per_repo: int = 2
    min_int_score: int = 4
    min_bytes: int = 200
    max_bytes: int = 100_000
    excerpt_chars: int = 512
    max_examples: int = 8
    seed: int = 20_250_814
    timeout_seconds: float = 30.0
    http_max_attempts: int = 4
    http_backoff_seconds: float = 0.5
    http_max_backoff_seconds: float = 4.0
    overwrite: bool = False


Transport = Callable[[str, float], HttpJsonResponse]
BlobFetcher = Callable[[str], bytes]


def validate_revision(revision: str) -> str:
    """Require a full lowercase commit hash; moving aliases are forbidden."""
    if not _REVISION_RE.fullmatch(revision):
        raise ValueError("expected_revision must be an exact lowercase 40-hex commit hash")
    return revision


def validate_config(config: InspectionConfig) -> None:
    validate_revision(config.expected_revision)
    if not 1 <= config.metadata_rows <= MAX_METADATA_ROWS:
        raise ValueError(f"metadata_rows must be in [1, {MAX_METADATA_ROWS}]")
    if not 1 <= config.window_size <= MAX_WINDOW_SIZE:
        raise ValueError(f"window_size must be in [1, {MAX_WINDOW_SIZE}]")
    if not 0 <= config.content_blobs <= MAX_CONTENT_BLOBS:
        raise ValueError(f"content_blobs must be in [0, {MAX_CONTENT_BLOBS}]")
    if config.content_blobs > config.metadata_rows:
        raise ValueError("content_blobs cannot exceed metadata_rows")
    if config.max_per_repo <= 0:
        raise ValueError("max_per_repo must be positive")
    if config.min_bytes < 0 or config.max_bytes < config.min_bytes:
        raise ValueError("require 0 <= min_bytes <= max_bytes")
    if config.excerpt_chars < 0:
        raise ValueError("excerpt_chars must be non-negative")
    if not 0 <= config.max_examples <= config.content_blobs:
        raise ValueError("max_examples must be in [0, content_blobs]")
    if not math.isfinite(config.timeout_seconds) or config.timeout_seconds <= 0:
        raise ValueError("timeout_seconds must be positive")
    if not 1 <= config.http_max_attempts <= MAX_HTTP_ATTEMPTS:
        raise ValueError(f"http_max_attempts must be in [1, {MAX_HTTP_ATTEMPTS}]")
    for name, value in (
        ("http_backoff_seconds", config.http_backoff_seconds),
        ("http_max_backoff_seconds", config.http_max_backoff_seconds),
    ):
        if not math.isfinite(value) or not 0 <= value <= MAX_HTTP_BACKOFF_SECONDS:
            raise ValueError(f"{name} must be finite and in [0, {MAX_HTTP_BACKOFF_SECONDS}]")
    if config.http_max_backoff_seconds < config.http_backoff_seconds:
        raise ValueError("http_max_backoff_seconds cannot be below http_backoff_seconds")
    if config.report_path == config.examples_path:
        raise ValueError("report_path and examples_path must differ")
    if config.cache_dir in {config.report_path, config.examples_path}:
        raise ValueError("cache_dir cannot be an output file")


def deterministic_windows(
    *, total_rows: int, sample_rows: int, window_size: int, seed: int
) -> list[Window]:
    """Choose exact, non-overlapping windows from equal-width table strata."""
    if total_rows <= 0:
        raise ValueError("total_rows must be positive")
    if sample_rows <= 0 or sample_rows > total_rows:
        raise ValueError("sample_rows must be in [1, total_rows]")
    if window_size <= 0:
        raise ValueError("window_size must be positive")

    window_count = math.ceil(sample_rows / window_size)
    lengths = [window_size] * window_count
    lengths[-1] = sample_rows - window_size * (window_count - 1)
    windows: list[Window] = []
    for stratum, length in enumerate(lengths):
        lower = total_rows * stratum // window_count
        upper = total_rows * (stratum + 1) // window_count
        if upper - lower < length:
            raise ValueError("a sampling stratum is smaller than its requested window")
        available_offsets = upper - lower - length + 1
        rank = hashlib.sha256(f"{seed}\0{stratum}".encode()).digest()
        jitter = int.from_bytes(rank[:8], "big") % available_offsets
        windows.append(Window(stratum=stratum, offset=lower + jitter, length=length))
    return windows


def _canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def urllib_json_transport(url: str, timeout_seconds: float) -> HttpJsonResponse:
    request = Request(url, headers={"User-Agent": "PetitGPT-source-inspection/1"})
    started = time.perf_counter()
    try:
        with urlopen(request, timeout=timeout_seconds) as response:  # noqa: S310
            body = response.read()
            http_status = int(response.status)
            headers = {key.lower(): value for key, value in response.headers.items()}
    except HTTPError as exc:
        try:
            body = exc.read()
            http_status = int(exc.code)
            headers = {key.lower(): value for key, value in exc.headers.items()}
        finally:
            exc.close()
    request_latency_seconds = time.perf_counter() - started
    if http_status == 200:
        payload = json.loads(body)
        if not isinstance(payload, dict):
            raise RuntimeError(f"datasets-server returned non-object JSON for {url}")
    else:
        payload = {}
    return HttpJsonResponse(
        payload=payload,
        headers=headers,
        body_sha256=hashlib.sha256(body).hexdigest(),
        http_status=http_status,
        body_bytes=len(body),
        request_latency_seconds=request_latency_seconds,
    )


class DatasetServerClient:
    def __init__(
        self,
        *,
        api_root: str,
        expected_revision: str,
        timeout_seconds: float,
        transport: Transport,
        max_attempts: int,
        backoff_seconds: float,
        max_backoff_seconds: float,
        sleeper: Callable[[float], None],
    ) -> None:
        self.api_root = api_root.rstrip("/")
        self.expected_revision = validate_revision(expected_revision)
        self.timeout_seconds = timeout_seconds
        self.transport = transport
        self.max_attempts = max_attempts
        self.backoff_seconds = backoff_seconds
        self.max_backoff_seconds = max_backoff_seconds
        self.sleeper = sleeper
        self.responses: list[dict[str, Any]] = []
        self.attempts: list[dict[str, Any]] = []
        self._request_ordinal = 0

    def _retry_delay(self, attempt: int) -> float:
        return min(self.backoff_seconds * (2 ** (attempt - 1)), self.max_backoff_seconds)

    def _record_exception_attempt(
        self,
        *,
        endpoint: str,
        params: Mapping[str, Any],
        request_ordinal: int,
        attempt: int,
        exc: BaseException,
        transient: bool,
        latency_seconds: float,
    ) -> float | None:
        retry_scheduled = transient and attempt < self.max_attempts
        delay = self._retry_delay(attempt) if retry_scheduled else None
        self.attempts.append({
            "request_ordinal": request_ordinal,
            "endpoint": endpoint,
            "parameters": dict(params),
            "attempt": attempt,
            "max_attempts": self.max_attempts,
            "outcome": (
                "transient_network_exception" if transient else "nonretryable_transport_exception"
            ),
            "transient": transient,
            "retry_scheduled": retry_scheduled,
            "backoff_before_next_attempt_seconds": delay,
            "http_status": None,
            "body_bytes": None,
            "body_sha256": None,
            "request_latency_seconds": latency_seconds,
            "x_revision": None,
            "revision_verified": False,
            "exception_type": type(exc).__name__,
            "error": str(exc)[:500],
        })
        return delay

    def _response_attempt_evidence(
        self,
        *,
        endpoint: str,
        params: Mapping[str, Any],
        request_ordinal: int,
        attempt: int,
        response: HttpJsonResponse,
        actual_revision: str | None,
        outcome: str,
        transient: bool,
        revision_verified: bool,
        retry_scheduled: bool,
        delay: float | None,
    ) -> dict[str, Any]:
        return {
            "request_ordinal": request_ordinal,
            "endpoint": endpoint,
            "parameters": dict(params),
            "attempt": attempt,
            "max_attempts": self.max_attempts,
            "outcome": outcome,
            "transient": transient,
            "retry_scheduled": retry_scheduled,
            "backoff_before_next_attempt_seconds": delay,
            "http_status": response.http_status,
            "body_bytes": response.body_bytes,
            "body_sha256": response.body_sha256,
            "request_latency_seconds": response.request_latency_seconds,
            "x_revision": actual_revision,
            "revision_verified": revision_verified,
            "exception_type": None,
            "error": None,
        }

    def _get(self, endpoint: str, params: Mapping[str, Any]) -> Mapping[str, Any]:
        url = f"{self.api_root}/{endpoint}?{urlencode(params)}"
        self._request_ordinal += 1
        request_ordinal = self._request_ordinal
        for attempt in range(1, self.max_attempts + 1):
            started = time.perf_counter()
            try:
                response = self.transport(url, self.timeout_seconds)
            except Exception as exc:
                latency_seconds = time.perf_counter() - started
                if not math.isfinite(latency_seconds) or latency_seconds < 0:
                    raise RuntimeError(
                        f"invalid transport exception latency at /{endpoint}"
                    ) from exc
                transient = isinstance(exc, (URLError, TimeoutError))
                delay = self._record_exception_attempt(
                    endpoint=endpoint,
                    params=params,
                    request_ordinal=request_ordinal,
                    attempt=attempt,
                    exc=exc,
                    transient=transient,
                    latency_seconds=latency_seconds,
                )
                if not transient:
                    raise
                if delay is None:
                    raise RuntimeError(
                        f"datasets-server transient network failure exhausted "
                        f"{self.max_attempts} attempts at /{endpoint}"
                    ) from exc
                self.sleeper(delay)
                continue

            headers = {str(key).lower(): str(value) for key, value in response.headers.items()}
            actual_revision = headers.get("x-revision")
            if response.body_bytes < 0:
                raise RuntimeError(f"datasets-server returned invalid body size at /{endpoint}")
            if not re.fullmatch(r"[0-9a-f]{64}", response.body_sha256):
                raise RuntimeError(f"datasets-server returned invalid body digest at /{endpoint}")
            if (
                not math.isfinite(response.request_latency_seconds)
                or response.request_latency_seconds < 0
            ):
                raise RuntimeError(
                    f"datasets-server returned invalid request latency at /{endpoint}"
                )

            transient = response.http_status in _TRANSIENT_HTTP_STATUSES
            retry_scheduled = transient and attempt < self.max_attempts
            delay = self._retry_delay(attempt) if retry_scheduled else None
            if transient:
                self.attempts.append(
                    self._response_attempt_evidence(
                        endpoint=endpoint,
                        params=params,
                        request_ordinal=request_ordinal,
                        attempt=attempt,
                        response=response,
                        actual_revision=actual_revision,
                        outcome="transient_http_status",
                        transient=True,
                        revision_verified=False,
                        retry_scheduled=retry_scheduled,
                        delay=delay,
                    )
                )
                if delay is None:
                    raise RuntimeError(
                        f"datasets-server transient HTTP {response.http_status} exhausted "
                        f"{self.max_attempts} attempts at /{endpoint}"
                    )
                self.sleeper(delay)
                continue

            if response.http_status != 200:
                self.attempts.append(
                    self._response_attempt_evidence(
                        endpoint=endpoint,
                        params=params,
                        request_ordinal=request_ordinal,
                        attempt=attempt,
                        response=response,
                        actual_revision=actual_revision,
                        outcome="nonretryable_http_status",
                        transient=False,
                        revision_verified=False,
                        retry_scheduled=False,
                        delay=None,
                    )
                )
                raise RuntimeError(
                    f"datasets-server returned nonretryable HTTP "
                    f"{response.http_status} at /{endpoint}"
                )

            if actual_revision != self.expected_revision:
                self.attempts.append(
                    self._response_attempt_evidence(
                        endpoint=endpoint,
                        params=params,
                        request_ordinal=request_ordinal,
                        attempt=attempt,
                        response=response,
                        actual_revision=actual_revision,
                        outcome="revision_mismatch",
                        transient=False,
                        revision_verified=False,
                        retry_scheduled=False,
                        delay=None,
                    )
                )
                raise RuntimeError(
                    f"datasets-server revision drift at /{endpoint}: "
                    f"expected {self.expected_revision}, got {actual_revision!r}"
                )

            evidence = self._response_attempt_evidence(
                endpoint=endpoint,
                params=params,
                request_ordinal=request_ordinal,
                attempt=attempt,
                response=response,
                actual_revision=actual_revision,
                outcome="success",
                transient=False,
                revision_verified=True,
                retry_scheduled=False,
                delay=None,
            )
            self.attempts.append(evidence)
            self.responses.append(evidence)
            return response.payload
        raise AssertionError("bounded retry loop terminated without returning or raising")

    def total_rows(self, *, dataset: str, config: str, split: str) -> int:
        payload = self._get("size", {"dataset": dataset})
        size = payload.get("size")
        if not isinstance(size, dict):
            raise RuntimeError("datasets-server /size response has no size object")
        splits = size.get("splits")
        if not isinstance(splits, list):
            raise RuntimeError("datasets-server /size response has no splits list")
        matches = [
            item
            for item in splits
            if isinstance(item, dict)
            and item.get("config") == config
            and item.get("split") == split
        ]
        if len(matches) != 1:
            raise RuntimeError(
                f"expected one /size entry for config={config!r}, split={split!r}; "
                f"found {len(matches)}"
            )
        try:
            total_rows = int(matches[0]["num_rows"])
        except (KeyError, TypeError, ValueError) as exc:
            raise RuntimeError("invalid num_rows in datasets-server /size response") from exc
        if total_rows <= 0:
            raise RuntimeError(f"datasets-server reported non-positive num_rows={total_rows}")
        return total_rows

    def rows(
        self,
        *,
        dataset: str,
        config: str,
        split: str,
        offset: int,
        length: int,
    ) -> tuple[list[dict[str, Any]], Any]:
        payload = self._get(
            "rows",
            {
                "dataset": dataset,
                "config": config,
                "split": split,
                "offset": offset,
                "length": length,
            },
        )
        rows = payload.get("rows")
        if not isinstance(rows, list) or len(rows) != length:
            actual = len(rows) if isinstance(rows, list) else "non-list"
            raise RuntimeError(f"expected {length} rows at offset {offset}, got {actual}")
        unpacked: list[dict[str, Any]] = []
        for position, wrapped in enumerate(rows):
            if not isinstance(wrapped, dict) or not isinstance(wrapped.get("row"), dict):
                raise RuntimeError(f"malformed datasets-server row at offset {offset + position}")
            row_index = wrapped.get("row_idx")
            if row_index != offset + position:
                raise RuntimeError(
                    f"row index mismatch: expected {offset + position}, got {row_index!r}"
                )
            if "row_idx" in wrapped["row"]:
                raise RuntimeError(
                    f"upstream row payload unexpectedly contains reserved row_idx at {row_index}"
                )
            unpacked.append({**wrapped["row"], "row_idx": row_index})
        return unpacked, payload.get("features")


def _stable_rank(row: Mapping[str, Any], *, seed: int) -> str:
    identity = "\0".join((
        str(seed),
        str(row.get("blob_id", "")),
        str(row.get("repo_name", "")),
        str(row.get("path", "")),
        str(row.get("row_idx", "")),
        str(row.get("length_bytes", "")),
        str(row.get("int_score", "")),
        str(row.get("score", "")),
    ))
    return hashlib.sha256(identity.encode("utf-8")).hexdigest()


def select_content_rows(
    rows: Sequence[Mapping[str, Any]],
    *,
    count: int,
    max_per_repo: int,
    min_int_score: int,
    min_bytes: int,
    max_bytes: int,
    seed: int,
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    """Select a stable, blob-deduplicated subset while limiting repo dominance."""
    rejected = Counter()
    eligible_candidates: list[dict[str, Any]] = []
    for raw_row in rows:
        row = dict(raw_row)
        blob_id = row.get("blob_id")
        repo_name = row.get("repo_name")
        try:
            int_score = int(row.get("int_score"))
            length_bytes = int(row.get("length_bytes"))
            score = float(row.get("score"))
        except (TypeError, ValueError):
            rejected["invalid_numeric_metadata"] += 1
            continue
        if not math.isfinite(score):
            rejected["non_finite_score"] += 1
            continue
        if not isinstance(blob_id, str) or not blob_id:
            rejected["missing_blob_id"] += 1
            continue
        if not isinstance(repo_name, str) or not repo_name:
            rejected["missing_repo_name"] += 1
            continue
        if int_score < min_int_score:
            rejected["below_min_int_score"] += 1
            continue
        if not min_bytes <= length_bytes <= max_bytes:
            rejected["outside_length_bounds"] += 1
            continue
        row["int_score"] = int_score
        row["length_bytes"] = length_bytes
        row["score"] = score
        eligible_candidates.append(row)

    # Sort before deduplication so duplicate metadata cannot make the chosen
    # canonical row depend on datasets-server response order.
    eligible: list[dict[str, Any]] = []
    seen_blobs: set[str] = set()
    for row in sorted(
        eligible_candidates,
        key=lambda value: (
            _stable_rank(value, seed=seed),
            _canonical_json_bytes(value),
        ),
    ):
        blob_id = str(row["blob_id"])
        if blob_id in seen_blobs:
            rejected["duplicate_blob_id"] += 1
            continue
        seen_blobs.add(blob_id)
        eligible.append(row)

    selected: list[dict[str, Any]] = []
    repo_counts: Counter[str] = Counter()
    for row in eligible:
        repo_name = str(row["repo_name"])
        if repo_counts[repo_name] >= max_per_repo:
            rejected["per_repo_cap"] += 1
            continue
        if len(selected) < count:
            selected.append(row)
            repo_counts[repo_name] += 1
        else:
            rejected["not_selected_by_count_limit"] += 1

    stats = {
        "requested": count,
        "eligible": len(eligible),
        "selected": len(selected),
        "underfill": count - len(selected),
        **{key: int(value) for key, value in sorted(rejected.items())},
    }
    return selected, stats


def _percentile(values: Sequence[int | float], percentile: float) -> float | None:
    if not values:
        return None
    ordered = sorted(float(value) for value in values)
    if len(ordered) == 1:
        return ordered[0]
    position = (len(ordered) - 1) * percentile
    lower = math.floor(position)
    upper = math.ceil(position)
    fraction = position - lower
    return ordered[lower] * (1 - fraction) + ordered[upper] * fraction


def _distribution(values: Sequence[int | float]) -> dict[str, float | int | None]:
    if not values:
        return {
            "count": 0,
            "min": None,
            "p50": None,
            "p90": None,
            "p99": None,
            "max": None,
            "mean": None,
        }
    return {
        "count": len(values),
        "min": min(values),
        "p50": _percentile(values, 0.50),
        "p90": _percentile(values, 0.90),
        "p99": _percentile(values, 0.99),
        "max": max(values),
        "mean": sum(values) / len(values),
    }


def _clock_value(clock: Callable[[], float]) -> float:
    value = float(clock())
    if not math.isfinite(value):
        raise RuntimeError(f"inspection clock returned non-finite value {value!r}")
    return value


def _elapsed_seconds(clock: Callable[[], float], started: float) -> float:
    finished = _clock_value(clock)
    if finished < started:
        raise RuntimeError(f"inspection clock moved backwards from {started!r} to {finished!r}")
    return finished - started


def _top_counts(counter: Counter[str], limit: int = 10) -> list[dict[str, Any]]:
    return [{"value": value, "count": count} for value, count in counter.most_common(limit)]


def _rate(numerator: int, denominator: int) -> dict[str, int | float | None]:
    return {
        "numerator": int(numerator),
        "denominator": int(denominator),
        "value": numerator / denominator if denominator else None,
    }


def metadata_metrics(rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    fields = sorted({str(key) for row in rows for key in row if key != "row_idx"})
    missing_required = sorted(_REQUIRED_FIELDS.difference(fields))
    lengths: list[int] = []
    scores: list[float] = []
    int_scores: Counter[str] = Counter()
    repos: Counter[str] = Counter()
    paths: Counter[str] = Counter()
    field_presence = Counter()
    invalid_numeric = 0
    non_finite_scores = 0
    for row in rows:
        for field in fields:
            if row.get(field) is not None:
                field_presence[field] += 1
        repos[str(row.get("repo_name", ""))] += 1
        paths[str(row.get("path", ""))] += 1
        try:
            length = int(row["length_bytes"])
            score = float(row["score"])
            int_score = int(row["int_score"])
            if not math.isfinite(score):
                non_finite_scores += 1
                continue
            lengths.append(length)
            scores.append(score)
            int_scores[str(int_score)] += 1
        except (KeyError, TypeError, ValueError):
            invalid_numeric += 1
    count = len(rows)
    return {
        "sampled_rows": count,
        "schema_fields": fields,
        "missing_required_fields": missing_required,
        "field_presence": {
            field: {
                "count": int(field_presence[field]),
                "denominator": count,
                "fraction": field_presence[field] / count if count else None,
            }
            for field in fields
        },
        "explicitly_checked_optional_fields": {
            field: _rate(sum(row.get(field) is not None for row in rows), count)
            for field in ("license", "src_encoding")
        },
        "invalid_numeric_rows": invalid_numeric,
        "non_finite_score_rows": non_finite_scores,
        "length_bytes": _distribution(lengths),
        "score": _distribution(scores),
        "int_score_counts": dict(sorted(int_scores.items())),
        "unique_repositories": len(repos),
        "unique_paths": len(paths),
        "top_repositories": _top_counts(repos),
        "top_paths": _top_counts(paths),
        "top_repository_rate": _rate(max(repos.values(), default=0), count),
        "top_five_repository_rate": _rate(sum(value for _, value in repos.most_common(5)), count),
    }


def _has_docstring(tree: ast.AST) -> bool:
    nodes = (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    return any(
        isinstance(node, nodes) and ast.get_docstring(node, clean=False) is not None
        for node in ast.walk(tree)
    )


def _has_comment(text: str) -> bool:
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        return any(token.type == tokenize.COMMENT for token in tokens)
    except (IndentationError, tokenize.TokenError):
        return False


def _repetition_metrics(text: str) -> dict[str, Any]:
    normalized = [line.strip() for line in text.splitlines() if line.strip()]
    counts = Counter(normalized)
    repeated_excess = sum(count - 1 for count in counts.values() if count > 1)
    ratio = repeated_excess / len(normalized) if normalized else 0.0
    maximum = max(counts.values(), default=0)
    flagged = len(normalized) >= 20 and (ratio >= 0.30 or maximum >= 5)
    return {
        "nonempty_lines": len(normalized),
        "repeated_line_excess": repeated_excess,
        "repeated_line_ratio": ratio,
        "max_identical_line_count": maximum,
        "heuristic_flag": flagged,
    }


def _fully_redacted_source_shape(text: str, max_characters: int) -> tuple[str, int]:
    excerpt = text[:max_characters]
    redacted = "".join(character if character.isspace() else "█" for character in excerpt)
    return redacted, sum(not character.isspace() for character in excerpt)


def analyze_source(row: Mapping[str, Any], raw: bytes, text: str) -> dict[str, Any]:
    path = str(row.get("path", ""))
    path_parts = {part for part in path.lower().replace("\\", "/").split("/") if part}
    header = "\n".join(text.splitlines()[:30]).lower()
    generated_markers = [marker for marker in _GENERATED_MARKERS if marker in header]
    try:
        tree = ast.parse(text, filename=path or "<blob>")
        ast_ok = True
        ast_error = None
        has_docstring = _has_docstring(tree)
    except (SyntaxError, ValueError) as exc:
        ast_ok = False
        ast_error = f"{type(exc).__name__}: {exc}"[:500]
        has_docstring = False
    expected_length = int(row["length_bytes"])
    repetition = _repetition_metrics(text)
    utf8_round_trip_exact = text.encode("utf-8") == raw
    return {
        "raw_bytes": len(raw),
        "raw_sha256": hashlib.sha256(raw).hexdigest(),
        "utf8_reencode_matches_raw": utf8_round_trip_exact,
        "metadata_length_bytes": expected_length,
        "metadata_length_delta": len(raw) - expected_length,
        "metadata_length_matches": len(raw) == expected_length,
        "text_characters": len(text),
        "line_count": len(text.splitlines()),
        "ast_parse_ok": ast_ok,
        "ast_error": ast_error,
        "has_docstring": has_docstring,
        "has_comment": _has_comment(text),
        "vendor_path_heuristic": bool(path_parts.intersection(_VENDOR_PATH_PARTS)),
        "generated_file_heuristic": bool(generated_markers),
        "generated_markers": generated_markers,
        "repetition": repetition,
    }


def _content_summary(records: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    attempted = len(records)
    decoded = [record for record in records if record["outcome"] == "decoded"]
    analyses = [record["analysis"] for record in decoded]
    latencies = [float(record["latency_seconds"]) for record in records]
    fetch_success = sum(record["outcome"] != "fetch_failed" for record in records)
    cache_hits = sum(record.get("cache_hit") is True for record in records)
    cache_misses = sum(record.get("cache_hit") is False for record in records)
    ast_parse_success = sum(analysis["ast_parse_ok"] for analysis in analyses)
    vendor_count = sum(analysis["vendor_path_heuristic"] for analysis in analyses)
    generated_count = sum(analysis["generated_file_heuristic"] for analysis in analyses)
    repetition_count = sum(analysis["repetition"]["heuristic_flag"] for analysis in analyses)
    docstring_count = sum(analysis["has_docstring"] for analysis in analyses)
    comment_count = sum(analysis["has_comment"] for analysis in analyses)
    metadata_length_matches = sum(analysis["metadata_length_matches"] for analysis in analyses)
    utf8_reencode_matches = sum(analysis["utf8_reencode_matches_raw"] for analysis in analyses)
    summary = {
        "attempted": attempted,
        "fetch_success": fetch_success,
        "fetch_failed": sum(record["outcome"] == "fetch_failed" for record in records),
        "strict_utf8_success": len(decoded),
        "strict_utf8_failed": sum(record["outcome"] == "decode_failed" for record in records),
        "cache_hits": cache_hits,
        "cache_misses": cache_misses,
        "cache_disabled": sum(record.get("cache_hit") is None for record in records),
        "latency_seconds": _distribution(latencies),
        "raw_bytes": _distribution([analysis["raw_bytes"] for analysis in analyses]),
        "utf8_reencode_matches_raw": utf8_reencode_matches,
        "utf8_reencode_mismatches_raw": sum(
            not analysis["utf8_reencode_matches_raw"] for analysis in analyses
        ),
        "metadata_length_matches": metadata_length_matches,
        "metadata_length_mismatches": sum(
            not analysis["metadata_length_matches"] for analysis in analyses
        ),
        "ast_parse_success": ast_parse_success,
        "ast_parse_failed": sum(not analysis["ast_parse_ok"] for analysis in analyses),
        "vendor_path_heuristic": vendor_count,
        "generated_file_heuristic": generated_count,
        "repetition_heuristic": repetition_count,
        "has_docstring": docstring_count,
        "has_comment": comment_count,
    }
    decoded_count = len(decoded)
    summary["rates"] = {
        "fetch_success": _rate(fetch_success, attempted),
        "strict_utf8_success": _rate(decoded_count, fetch_success),
        "cache_hit": _rate(cache_hits, cache_hits + cache_misses),
        "utf8_reencode_matches_raw": _rate(utf8_reencode_matches, decoded_count),
        "metadata_length_matches": _rate(metadata_length_matches, decoded_count),
        "ast_parse_success": _rate(ast_parse_success, decoded_count),
        "vendor_path_heuristic": _rate(vendor_count, decoded_count),
        "generated_file_heuristic": _rate(generated_count, decoded_count),
        "repetition_heuristic": _rate(repetition_count, decoded_count),
        "has_docstring": _rate(docstring_count, decoded_count),
        "has_comment": _rate(comment_count, decoded_count),
    }
    return summary


def _fsync_parent(path: Path) -> None:
    flags = getattr(os, "O_DIRECTORY", 0) | os.O_RDONLY
    try:
        fd = os.open(str(path.parent), flags)
    except OSError:
        return
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _write_bytes_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        with open(temporary, "xb") as output:
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
        _fsync_parent(path)
    finally:
        temporary.unlink(missing_ok=True)


def _preflight_outputs(config: InspectionConfig) -> None:
    if config.report_path.exists() and not config.overwrite:
        raise FileExistsError(
            f"refusing to replace existing inspection report: {config.report_path}"
        )


def _content_addressed_path(path: Path, digest: str) -> Path:
    return path.with_name(f"{path.stem}.sha256-{digest}{path.suffix}")


def _publish_content_addressed(path: Path, data: bytes) -> None:
    if path.exists():
        if path.read_bytes() != data:
            raise RuntimeError(f"content-address collision at {path}")
        return
    _write_bytes_atomic(path, data)


def _schema_fingerprint(features: Any, row_fields: Sequence[str]) -> str:
    return hashlib.sha256(
        _canonical_json_bytes({"features": features, "row_fields": list(row_fields)})
    ).hexdigest()


def inspect_python_source(
    config: InspectionConfig,
    *,
    transport: Transport = urllib_json_transport,
    blob_fetcher: BlobFetcher | None = None,
    clock: Callable[[], float] = time.perf_counter,
    sleeper: Callable[[float], None] = time.sleep,
) -> dict[str, Any]:
    """Execute the bounded inspection and atomically publish its evidence."""
    validate_config(config)
    _preflight_outputs(config)
    client = DatasetServerClient(
        api_root=config.api_root,
        expected_revision=config.expected_revision,
        timeout_seconds=config.timeout_seconds,
        transport=transport,
        max_attempts=config.http_max_attempts,
        backoff_seconds=config.http_backoff_seconds,
        max_backoff_seconds=config.http_max_backoff_seconds,
        sleeper=sleeper,
    )
    total_rows = client.total_rows(
        dataset=config.dataset,
        config=config.dataset_config,
        split=config.split,
    )
    if config.metadata_rows > total_rows:
        raise RuntimeError(
            f"metadata_rows={config.metadata_rows} exceeds dataset row count {total_rows}"
        )
    windows = deterministic_windows(
        total_rows=total_rows,
        sample_rows=config.metadata_rows,
        window_size=config.window_size,
        seed=config.seed,
    )

    metadata_rows: list[dict[str, Any]] = []
    expected_features: Any = None
    expected_row_fields: list[str] | None = None
    for window in windows:
        rows, features = client.rows(
            dataset=config.dataset,
            config=config.dataset_config,
            split=config.split,
            offset=window.offset,
            length=window.length,
        )
        row_fields = sorted(key for key in rows[0] if key != "row_idx")
        if expected_row_fields is None:
            expected_features = features
            expected_row_fields = row_fields
        elif features != expected_features or row_fields != expected_row_fields:
            raise RuntimeError("datasets-server schema drifted between sampled windows")
        for row in rows:
            if sorted(key for key in row if key != "row_idx") != expected_row_fields:
                raise RuntimeError(f"row-level schema drift at row_idx={row['row_idx']}")
        metadata_rows.extend(rows)

    metadata = metadata_metrics(metadata_rows)
    if metadata["missing_required_fields"]:
        raise RuntimeError(
            f"metadata schema lacks required fields: {metadata['missing_required_fields']}"
        )
    selected, selection = select_content_rows(
        metadata_rows,
        count=config.content_blobs,
        max_per_repo=config.max_per_repo,
        min_int_score=config.min_int_score,
        min_bytes=config.min_bytes,
        max_bytes=config.max_bytes,
        seed=config.seed,
    )

    injected_blob_fetcher = blob_fetcher is not None
    if blob_fetcher is None and selected:
        blob_fetcher = make_software_heritage_fetcher()
    content_records: list[dict[str, Any]] = []
    example_records: list[dict[str, Any]] = []
    for row in selected:
        started = _clock_value(clock)
        cache_hit: bool | None = None
        try:
            if blob_fetcher is None:
                raise RuntimeError("blob fetcher is unavailable")
            raw, cache_hit = fetch_blob_cached(str(row["blob_id"]), blob_fetcher, config.cache_dir)
        except Exception as exc:
            record: dict[str, Any] = {
                "row_idx": row["row_idx"],
                "blob_id": row["blob_id"],
                "repo_name": row["repo_name"],
                "path": row.get("path", ""),
                "outcome": "fetch_failed",
                "cache_hit": cache_hit,
                "error": f"{type(exc).__name__}: {exc}"[:500],
                "latency_seconds": _elapsed_seconds(clock, started),
            }
            content_records.append(record)
            continue

        try:
            text = decode_blob_bytes(raw, blob_id=str(row["blob_id"]))
        except UnicodeDecodeError as exc:
            record = {
                "row_idx": row["row_idx"],
                "blob_id": row["blob_id"],
                "repo_name": row["repo_name"],
                "path": row.get("path", ""),
                "outcome": "decode_failed",
                "cache_hit": cache_hit,
                "raw_bytes": len(raw),
                "error": str(exc)[:500],
                "latency_seconds": _elapsed_seconds(clock, started),
            }
            content_records.append(record)
            continue

        analysis = analyze_source(row, raw, text)
        record = {
            "row_idx": row["row_idx"],
            "blob_id": row["blob_id"],
            "repo_name": row["repo_name"],
            "path": row.get("path", ""),
            "score": row.get("score"),
            "int_score": row["int_score"],
            "outcome": "decoded",
            "cache_hit": cache_hit,
            "latency_seconds": _elapsed_seconds(clock, started),
            "analysis": analysis,
        }
        content_records.append(record)
        if len(example_records) < config.max_examples:
            redacted_excerpt, redacted_characters = _fully_redacted_source_shape(
                text, config.excerpt_chars
            )
            example_records.append({
                **record,
                "content_handling": "private_fully_character_redacted_source_shape",
                "excerpt": redacted_excerpt,
                "excerpt_truncated": len(text) > config.excerpt_chars,
                "redaction": {
                    "strategy": "replace_every_non_whitespace_character_v1",
                    "characters_replaced": redacted_characters,
                    "source_characters_exposed": 0,
                },
            })

    examples_bytes = b"".join(_canonical_json_bytes(example) + b"\n" for example in example_records)
    examples_sha256 = hashlib.sha256(examples_bytes).hexdigest()
    actual_examples_path = _content_addressed_path(config.examples_path, examples_sha256)
    content_summary = _content_summary(content_records)
    connectivity_criteria = {
        "revision_verified_on_every_api_response": all(
            response["x_revision"] == config.expected_revision for response in client.responses
        ),
        "schema_contains_required_fields": not metadata["missing_required_fields"],
        "schema_consistent_across_windows": True,
        "exact_metadata_sample_count": len(metadata_rows) == config.metadata_rows,
        "exact_requested_content_selection": selection["selected"] == config.content_blobs,
        "at_least_one_blob_strictly_decoded": content_summary["strict_utf8_success"] > 0,
    }
    connectivity_status = "PASS" if all(connectivity_criteria.values()) else "FAIL"
    report: dict[str, Any] = {
        "schema_version": 1,
        "kind": "petitgpt_bounded_python_source_inspection",
        "status": "complete",
        "scope": "bounded_inspection_only",
        "decision_scope": "NOT_SOURCE_APPROVAL",
        "connectivity_gate": {
            "name": "P0_DATASET_AND_BLOB_CONNECTIVITY",
            "status": connectivity_status,
            "scope": "CONNECTIVITY_ONLY_NOT_SOURCE_APPROVAL",
            "criteria": connectivity_criteria,
        },
        "dataset": {
            "name": config.dataset,
            "config": config.dataset_config,
            "split": config.split,
            "expected_revision": config.expected_revision,
            "verified_revision": config.expected_revision,
            "total_rows": total_rows,
        },
        "inspection_config": {
            "datasets_server": {
                "api_root": config.api_root,
                "size_path": "/size?dataset=<dataset>",
                "rows_path": (
                    "/rows?dataset=<dataset>&config=<config>&split=<split>"
                    "&offset=<offset>&length=<length>"
                ),
                "timeout_seconds": config.timeout_seconds,
                "retry_policy": {
                    "max_attempts_per_request": config.http_max_attempts,
                    "backoff_strategy": "deterministic_exponential_capped_v1",
                    "initial_backoff_seconds": config.http_backoff_seconds,
                    "maximum_backoff_seconds": config.http_max_backoff_seconds,
                    "retryable_http_statuses": sorted(_TRANSIENT_HTTP_STATUSES),
                    "retryable_exception_types": ["URLError", "TimeoutError"],
                    "retry_after_header_honored": False,
                    "revision_or_schema_error_retryable": False,
                },
            },
            "bounds": {
                "metadata_rows": config.metadata_rows,
                "window_size": config.window_size,
                "content_blobs": config.content_blobs,
                "max_examples": config.max_examples,
                "excerpt_characters": config.excerpt_chars,
            },
            "selection_thresholds": {
                "min_int_score": config.min_int_score,
                "min_bytes": config.min_bytes,
                "max_bytes": config.max_bytes,
                "max_per_repo": config.max_per_repo,
            },
            "blob_backend": {
                "kind": (
                    "injected_custom_fetcher"
                    if injected_blob_fetcher
                    else "software_heritage_public_s3_unsigned_gzip"
                ),
                "bucket": None if injected_blob_fetcher else "softwareheritage",
                "object_key_template": None if injected_blob_fetcher else "content/{blob_id}",
                "region": None if injected_blob_fetcher else "us-west-2",
                "authentication": None if injected_blob_fetcher else "unsigned_anonymous",
                "object_encoding": None if injected_blob_fetcher else "gzip",
                "decompression_contract": (
                    None
                    if injected_blob_fetcher
                    else "gzip_decompress_object_before_strict_utf8_decode"
                ),
                "cached_payload": "decompressed_raw_blob_bytes",
            },
            "cache_dir": str(config.cache_dir) if config.cache_dir is not None else None,
        },
        "sampling": {
            "seed": config.seed,
            "strategy": "seeded_contiguous_window_within_equal_row_index_strata_v1",
            "requested_metadata_rows": config.metadata_rows,
            "sampled_metadata_rows": len(metadata_rows),
            "window_size": config.window_size,
            "windows": [asdict(window) for window in windows],
        },
        "api_evidence": {
            "verified_successful_responses": client.responses,
            "all_request_attempts": client.attempts,
            "request_count": client._request_ordinal,
            "attempt_count": len(client.attempts),
            "retry_count": len(client.attempts) - len(client.responses),
        },
        "metadata_schema": {
            "features": expected_features,
            "row_fields": expected_row_fields,
            "fingerprint": _schema_fingerprint(expected_features, expected_row_fields or []),
        },
        "sampled_row_identifiers": [
            {
                "row_idx": row["row_idx"],
                "blob_id": row.get("blob_id"),
                "repo_name": row.get("repo_name"),
                "path": row.get("path"),
            }
            for row in metadata_rows
        ],
        "metadata_metrics": metadata,
        "content_selection": selection,
        "content_metrics": content_summary,
        "content_records": content_records,
        "outputs": {
            "examples_path_namespace": str(config.examples_path),
            "examples_path": str(actual_examples_path),
            "examples_count": len(example_records),
            "examples_sha256": examples_sha256,
            "examples_content_handling": "PRIVATE_FULLY_CHARACTER_REDACTED_SOURCE_SHAPES",
            "examples_git_policy": "DO_NOT_COMMIT",
            "cache_dir": str(config.cache_dir) if config.cache_dir is not None else None,
        },
        "limits": {
            "metadata_rows_hard_cap": MAX_METADATA_ROWS,
            "content_blobs_hard_cap": MAX_CONTENT_BLOBS,
            "rows_api_window_hard_cap": MAX_WINDOW_SIZE,
            "full_dataset_downloaded": False,
            "full_yield_estimate_supported": False,
            "token_yield_estimate_supported": False,
            "note": (
                "This bounded sample checks connectivity, schema, decoding, and coarse "
                "quality signals only. It cannot establish corpus-wide acceptance or final-tokenizer "
                "yield; run the separately approved larger inspection before freezing quotas."
            ),
        },
    }
    report_bytes = (
        json.dumps(
            report,
            allow_nan=False,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        ).encode("utf-8")
        + b"\n"
    )

    # The fixed-name report is the commit marker. The immutable examples object
    # is content-addressed and made durable first, so an older report can never
    # silently begin referring to new examples after an interrupted overwrite.
    _publish_content_addressed(actual_examples_path, examples_bytes)
    _write_bytes_atomic(config.report_path, report_bytes)
    return report


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Boundedly inspect revision-pinned SmolLM python-edu metadata and blobs."
    )
    parser.add_argument("--expected_revision", required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--examples", type=Path, default=None)
    parser.add_argument("--cache_dir", type=Path, default=None)
    parser.add_argument("--no_cache", action="store_true")
    parser.add_argument("--dataset", default=DEFAULT_DATASET)
    parser.add_argument("--dataset_config", default=DEFAULT_CONFIG)
    parser.add_argument("--split", default=DEFAULT_SPLIT)
    parser.add_argument("--api_root", default=DEFAULT_API_ROOT)
    parser.add_argument("--metadata_rows", type=int, default=25)
    parser.add_argument("--window_size", type=int, default=5)
    parser.add_argument("--content_blobs", type=int, default=8)
    parser.add_argument("--max_per_repo", type=int, default=2)
    parser.add_argument("--min_int_score", type=int, default=4)
    parser.add_argument("--min_bytes", type=int, default=200)
    parser.add_argument("--max_bytes", type=int, default=100_000)
    parser.add_argument("--excerpt_chars", type=int, default=512)
    parser.add_argument("--max_examples", type=int, default=8)
    parser.add_argument("--seed", type=int, default=20_250_814)
    parser.add_argument("--timeout_seconds", type=float, default=30.0)
    parser.add_argument("--http_max_attempts", type=int, default=4)
    parser.add_argument("--http_backoff_seconds", type=float, default=0.5)
    parser.add_argument("--http_max_backoff_seconds", type=float, default=4.0)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    report_path = args.report
    examples_path = args.examples or report_path.with_suffix(".examples.jsonl")
    cache_dir = None
    if not args.no_cache:
        cache_dir = args.cache_dir or report_path.parent / "blob_cache"
    config = InspectionConfig(
        expected_revision=args.expected_revision,
        report_path=report_path,
        examples_path=examples_path,
        cache_dir=cache_dir,
        dataset=args.dataset,
        dataset_config=args.dataset_config,
        split=args.split,
        api_root=args.api_root,
        metadata_rows=args.metadata_rows,
        window_size=args.window_size,
        content_blobs=args.content_blobs,
        max_per_repo=args.max_per_repo,
        min_int_score=args.min_int_score,
        min_bytes=args.min_bytes,
        max_bytes=args.max_bytes,
        excerpt_chars=args.excerpt_chars,
        max_examples=args.max_examples,
        seed=args.seed,
        timeout_seconds=args.timeout_seconds,
        http_max_attempts=args.http_max_attempts,
        http_backoff_seconds=args.http_backoff_seconds,
        http_max_backoff_seconds=args.http_max_backoff_seconds,
        overwrite=args.overwrite,
    )
    report = inspect_python_source(config)
    print(
        json.dumps(
            report,
            allow_nan=False,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    )
    if report["connectivity_gate"]["status"] != "PASS":
        raise SystemExit(2)


if __name__ == "__main__":
    main()
