"""Pure, source-text-free quality metrics for bounded Python inspections.

The functions in this module perform no network or filesystem I/O.  They accept
already-resolved bytes/text, return JSON-safe aggregate evidence, and never
return source text, source lines, identifiers, literals, or paths.  All
canonicalization is detection-only: retained training text is not rewritten.
"""

from __future__ import annotations

import ast
from collections import Counter
from collections.abc import Collection, Mapping, Sequence
import hashlib
import io
import math
import sys
import tokenize
from typing import Any

MIN_SOURCE_BYTES = 200
MAX_SOURCE_BYTES = 100_000
BINARY_CONTROL_RATIO = 0.01
MIN_REPETITION_LINES = 20
MAX_REPEATED_LINE_RATIO = 0.30
MAX_IDENTICAL_LINE_COUNT = 5
MINIFIED_MAX_NONEMPTY_LINES = 2
MINIFIED_MIN_MAX_LINE_LENGTH = 500
CHARS_PER_TOKEN_SENSITIVITY = (2.0, 2.5, 3.0, 3.5, 4.0)
YIELD_TARGETS = (1_100_000_000, 1_600_000_000, 2_100_000_000)
HARD_GATE_ORDER = (
    "utf8_round_trip",
    "size_200_to_100000_bytes",
    "nonempty_nonwhitespace",
    "not_binary_like",
    "python3_ast_parse",
    "not_generated",
    "not_vendor",
    "not_pathological_repetition",
)

_VENDOR_PATH_PARTS = frozenset({
    "3rdparty",
    "deps",
    "external",
    "node_modules",
    "site-packages",
    "third_party",
    "thirdparty",
    "vendor",
    "vendored",
})
_GENERATED_PATH_PARTS = frozenset({"autogen", "autogenerated", "generated"})
_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "generated by",
    "generated file",
)
_LICENSE_HEADER_MARKERS = (
    "apache license",
    "copyright",
    "gnu general public license",
    "licensed under",
    "permission is hereby granted",
    "spdx-license-identifier",
)
_CONFIG_BASENAMES = frozenset({
    "config.py",
    "configuration.py",
    "conftest.py",
    "settings.py",
    "setup.cfg",
    "setup.py",
})
_CONFIG_PATH_PARTS = frozenset({"config", "configs", "configuration", "settings"})
_LOCK_PATH_PARTS = frozenset({"lock", "locks"})
_TEST_PATH_PARTS = frozenset({"test", "testing", "tests"})
_ALLOWED_C0 = frozenset({"\t", "\n", "\f", "\r"})
_AST_FINGERPRINT_DOMAIN = b"PetitGPT-python-ast-detection-v1\0"
_BOOTSTRAP_DOMAIN = b"PetitGPT-python-quality-bootstrap-v1\0"

_AST_COUNT_NAMES = (
    "Assert",
    "AsyncFor",
    "AsyncFunctionDef",
    "AsyncWith",
    "Await",
    "Call",
    "ClassDef",
    "DictComp",
    "ExceptHandler",
    "For",
    "FunctionDef",
    "GeneratorExp",
    "Import",
    "ImportFrom",
    "Lambda",
    "ListComp",
    "Match",
    "Raise",
    "Return",
    "SetComp",
    "Try",
    "TryStar",
    "While",
    "With",
    "Yield",
    "YieldFrom",
)


def _rate(numerator: int | float, denominator: int | float) -> dict[str, int | float | None]:
    return {
        "numerator": numerator,
        "denominator": denominator,
        "value": numerator / denominator if denominator else None,
    }


def _path_signals(path: str) -> dict[str, bool]:
    normalized = path.casefold().replace("\\", "/")
    parts = tuple(part for part in normalized.split("/") if part)
    part_set = set(parts)
    basename = parts[-1] if parts else ""
    is_test = bool(part_set.intersection(_TEST_PATH_PARTS)) or (
        basename.startswith("test_") or basename.endswith("_test.py") or basename == "conftest.py"
    )
    is_config = (
        basename in _CONFIG_BASENAMES
        or bool(part_set.intersection(_CONFIG_PATH_PARTS))
        or basename.endswith((".cfg", ".ini", ".toml", ".yaml", ".yml"))
    )
    is_lock = (
        bool(part_set.intersection(_LOCK_PATH_PARTS))
        or basename.endswith(".lock")
        or basename in {"lock.py", "locks.py"}
        or basename.startswith("lock_")
        or basename.endswith("_lock.py")
    )
    is_notebook = basename.endswith(".ipynb") or ".ipynb_checkpoints" in part_set
    generated_path = bool(part_set.intersection(_GENERATED_PATH_PARTS)) or basename.endswith((
        "_pb2.py",
        "_pb2_grpc.py",
    ))
    return {
        "vendor": bool(part_set.intersection(_VENDOR_PATH_PARTS)),
        "generated": generated_path,
        "test": is_test,
        "config": is_config,
        "lock": is_lock,
        "notebook": is_notebook,
    }


def _comment_metrics(text: str) -> dict[str, Any]:
    count = 0
    characters = 0
    scan_complete = True
    try:
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type == tokenize.COMMENT:
                count += 1
                characters += len(token.string)
    except (IndentationError, SyntaxError, tokenize.TokenError):
        scan_complete = False
    return {
        "count": count,
        "characters": characters,
        "character_share": characters / len(text) if text else None,
        "token_scan_complete": scan_complete,
    }


def _docstring_metrics(tree: ast.AST | None, text_characters: int) -> dict[str, Any]:
    if tree is None:
        return {
            "available": False,
            "count": 0,
            "characters": 0,
            "character_share": None,
        }
    count = 0
    characters = 0
    documented_nodes = (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    for node in ast.walk(tree):
        if not isinstance(node, documented_nodes):
            continue
        value = ast.get_docstring(node, clean=False)
        if value is not None:
            count += 1
            characters += len(value)
    return {
        "available": True,
        "count": count,
        "characters": characters,
        "character_share": characters / text_characters if text_characters else None,
    }


def _repetition_metrics(text: str) -> dict[str, Any]:
    normalized = [line.strip() for line in text.splitlines() if line.strip()]
    counts = Counter(normalized)
    repeated_excess = sum(count - 1 for count in counts.values() if count > 1)
    repeated_ratio = repeated_excess / len(normalized) if normalized else 0.0
    maximum = max(counts.values(), default=0)
    flagged = len(normalized) >= MIN_REPETITION_LINES and (
        repeated_ratio >= MAX_REPEATED_LINE_RATIO or maximum >= MAX_IDENTICAL_LINE_COUNT
    )
    return {
        "detection_only": True,
        "nonempty_lines": len(normalized),
        "repeated_line_excess": repeated_excess,
        "repeated_line_ratio": repeated_ratio,
        "max_identical_line_count": maximum,
        "heuristic_flag": flagged,
        "thresholds": {
            "minimum_nonempty_lines": MIN_REPETITION_LINES,
            "minimum_repeated_line_ratio": MAX_REPEATED_LINE_RATIO,
            "minimum_identical_line_count": MAX_IDENTICAL_LINE_COUNT,
        },
    }


def _ast_construct_metrics(tree: ast.AST | None) -> dict[str, Any]:
    counts = Counter(type(node).__name__ for node in ast.walk(tree)) if tree else Counter()
    detailed = {name: int(counts[name]) for name in _AST_COUNT_NAMES}
    return {
        "available": tree is not None,
        "counts": detailed,
        "groups": {
            "function_definitions": detailed["FunctionDef"] + detailed["AsyncFunctionDef"],
            "classes": detailed["ClassDef"],
            "import_statements": detailed["Import"] + detailed["ImportFrom"],
            "exception_constructs": (
                detailed["Try"]
                + detailed["TryStar"]
                + detailed["ExceptHandler"]
                + detailed["Raise"]
            ),
            "comprehensions": (
                detailed["ListComp"]
                + detailed["SetComp"]
                + detailed["DictComp"]
                + detailed["GeneratorExp"]
            ),
        },
    }


def _import_metrics(tree: ast.AST | None, stdlib_modules: Collection[str]) -> dict[str, Any]:
    catalog = frozenset(str(name) for name in stdlib_modules)
    catalog_sha256 = hashlib.sha256("\n".join(sorted(catalog)).encode("utf-8")).hexdigest()
    statements = 0
    imported_names = 0
    absolute_stdlib = 0
    absolute_nonstdlib = 0
    relative = 0
    wildcard = 0
    if tree is not None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                statements += 1
                for alias in node.names:
                    imported_names += 1
                    root = alias.name.partition(".")[0]
                    if root in catalog:
                        absolute_stdlib += 1
                    else:
                        absolute_nonstdlib += 1
            elif isinstance(node, ast.ImportFrom):
                statements += 1
                for alias in node.names:
                    imported_names += 1
                    wildcard += alias.name == "*"
                    if node.level:
                        relative += 1
                    else:
                        root = (node.module or "").partition(".")[0]
                        if root in catalog:
                            absolute_stdlib += 1
                        else:
                            absolute_nonstdlib += 1
    absolute = absolute_stdlib + absolute_nonstdlib
    return {
        "available": tree is not None,
        "stdlib_catalog": {
            "kind": "explicit_module_name_set",
            "count": len(catalog),
            "sha256": catalog_sha256,
        },
        "statements": statements,
        "imported_names": imported_names,
        "absolute_stdlib_names": absolute_stdlib,
        "absolute_nonstdlib_or_local_names": absolute_nonstdlib,
        "relative_names": relative,
        "wildcard_names": wildcard,
        "proxies": {
            "no_imports": imported_names == 0,
            "absolute_imports_are_stdlib_only": absolute > 0 and absolute_nonstdlib == 0,
            "has_nonstdlib_or_local_absolute_import": absolute_nonstdlib > 0,
            "has_relative_import": relative > 0,
            "has_wildcard_import": wildcard > 0,
        },
    }


def _is_docstring_statement(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def _is_main_guard(node: ast.AST) -> bool:
    if not isinstance(node, ast.If) or not isinstance(node.test, ast.Compare):
        return False
    comparison = node.test
    if len(comparison.ops) != 1 or not isinstance(comparison.ops[0], ast.Eq):
        return False
    if len(comparison.comparators) != 1:
        return False
    left = comparison.left
    right = comparison.comparators[0]

    def name_and_main(first: ast.AST, second: ast.AST) -> bool:
        return (
            isinstance(first, ast.Name)
            and first.id == "__name__"
            and isinstance(second, ast.Constant)
            and second.value == "__main__"
        )

    return name_and_main(left, right) or name_and_main(right, left)


def _is_not_implemented_raise(node: ast.AST) -> bool:
    if not isinstance(node, ast.Raise) or node.exc is None:
        return False
    target = node.exc.func if isinstance(node.exc, ast.Call) else node.exc
    return isinstance(target, ast.Name) and target.id == "NotImplementedError"


def _boilerplate_descriptors(
    tree: ast.AST | None,
    *,
    comment_metrics: Mapping[str, Any],
    docstring_metrics: Mapping[str, Any],
    text_characters: int,
    license_header_marker_count: int,
) -> dict[str, Any]:
    if not isinstance(tree, ast.Module):
        return {
            "descriptive_only_not_a_hard_gate": True,
            "available": False,
            "top_level_statement_count": 0,
            "top_level_executable_statement_count": 0,
            "only_imports_assignments_and_docstring": False,
            "only_declarations_imports_assignments_and_docstring": False,
            "stub_statement_count": 0,
            "not_implemented_raise_count": 0,
            "has_main_guard": False,
            "license_header_marker_count": license_header_marker_count,
            "comment_plus_docstring_character_share": None,
            "comment_or_docstring_dominant_at_50_percent": False,
        }
    body = list(tree.body)
    effective = body[1:] if body and _is_docstring_statement(body[0]) else body
    import_or_assignment = (ast.Import, ast.ImportFrom, ast.Assign, ast.AnnAssign, ast.AugAssign)
    declaration = import_or_assignment + (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
    executable = sum(not isinstance(node, declaration) for node in effective)
    stub_count = sum(
        isinstance(node, ast.Pass)
        or (
            isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and node.value.value is Ellipsis
        )
        for node in ast.walk(tree)
    )
    not_implemented = sum(_is_not_implemented_raise(node) for node in ast.walk(tree))
    descriptive_characters = int(comment_metrics["characters"]) + int(
        docstring_metrics["characters"]
    )
    descriptive_share = descriptive_characters / text_characters if text_characters else None
    return {
        "descriptive_only_not_a_hard_gate": True,
        "available": True,
        "top_level_statement_count": len(body),
        "top_level_executable_statement_count": executable,
        "only_imports_assignments_and_docstring": bool(body)
        and all(isinstance(node, import_or_assignment) for node in effective),
        "only_declarations_imports_assignments_and_docstring": bool(body)
        and all(isinstance(node, declaration) for node in effective),
        "stub_statement_count": stub_count,
        "not_implemented_raise_count": not_implemented,
        "has_main_guard": any(_is_main_guard(node) for node in body),
        "license_header_marker_count": license_header_marker_count,
        "comment_plus_docstring_character_share": descriptive_share,
        "comment_or_docstring_dominant_at_50_percent": (
            descriptive_share is not None and descriptive_share >= 0.50
        ),
    }


def _ast_fingerprint(tree: ast.AST | None) -> dict[str, Any]:
    runtime = f"{sys.version_info.major}.{sys.version_info.minor}"
    if tree is None:
        return {
            "available": False,
            "sha256": None,
            "algorithm": "sha256-domain-separated-ast-dump-no-attributes-v1",
            "python_ast_runtime": runtime,
            "detection_only": True,
            "training_text_modified": False,
        }
    canonical = ast.dump(tree, annotate_fields=True, include_attributes=False).encode("utf-8")
    digest = hashlib.sha256()
    digest.update(_AST_FINGERPRINT_DOMAIN)
    digest.update(len(canonical).to_bytes(8, "big", signed=False))
    digest.update(canonical)
    return {
        "available": True,
        "sha256": digest.hexdigest(),
        "algorithm": "sha256-domain-separated-ast-dump-no-attributes-v1",
        "python_ast_runtime": runtime,
        "detection_only": True,
        "training_text_modified": False,
    }


def analyze_python_source(
    raw: bytes,
    text: str,
    *,
    path: str = "",
    stdlib_modules: Collection[str] | None = None,
) -> dict[str, Any]:
    """Return source-free quality evidence for one already-resolved Python file."""
    if not isinstance(raw, bytes):
        raise TypeError("raw must be bytes")
    if not isinstance(text, str):
        raise TypeError("text must be str")
    if not isinstance(path, str):
        raise TypeError("path must be str")
    catalog = sys.stdlib_module_names if stdlib_modules is None else stdlib_modules

    try:
        reencoded = text.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        utf8_round_trip = False
    else:
        utf8_round_trip = reencoded == raw

    lines = text.splitlines()
    nonempty_lines = [line for line in lines if line.strip()]
    max_line_length = max((len(line) for line in lines), default=0)
    empty = text == ""
    whitespace_only = bool(text) and not text.strip()
    nul_present = "\x00" in text
    disallowed_c0_count = sum(
        ord(character) < 0x20 and character not in _ALLOWED_C0 for character in text
    )
    disallowed_c0_ratio = disallowed_c0_count / len(text) if text else 0.0
    binary_like = nul_present or disallowed_c0_ratio > BINARY_CONTROL_RATIO
    size_ok = MIN_SOURCE_BYTES <= len(raw) <= MAX_SOURCE_BYTES
    minified = (
        len(nonempty_lines) <= MINIFIED_MAX_NONEMPTY_LINES
        and max_line_length >= MINIFIED_MIN_MAX_LINE_LENGTH
    )

    header = "\n".join(lines[:30]).casefold()
    generated_marker_count = sum(marker in header for marker in _GENERATED_MARKERS)
    license_header_marker_count = sum(marker in header for marker in _LICENSE_HEADER_MARKERS)
    path_signals = _path_signals(path)
    generated = generated_marker_count > 0 or path_signals["generated"]
    repetition = _repetition_metrics(text)

    tree: ast.AST | None
    ast_error: dict[str, int | str | None] | None
    try:
        tree = ast.parse(text, filename="<inspected-python-source>", mode="exec")
    except (SyntaxError, ValueError) as exc:
        tree = None
        ast_error = {
            "type": type(exc).__name__,
            "lineno": getattr(exc, "lineno", None),
            "offset": getattr(exc, "offset", None),
        }
    else:
        ast_error = None

    comments = _comment_metrics(text)
    docstrings = _docstring_metrics(tree, len(text))
    constructs = _ast_construct_metrics(tree)
    imports = _import_metrics(tree, catalog)
    boilerplate = _boilerplate_descriptors(
        tree,
        comment_metrics=comments,
        docstring_metrics=docstrings,
        text_characters=len(text),
        license_header_marker_count=license_header_marker_count,
    )
    hard_gates = {
        "utf8_round_trip": utf8_round_trip,
        "size_200_to_100000_bytes": size_ok,
        "nonempty_nonwhitespace": not (empty or whitespace_only),
        "not_binary_like": not binary_like,
        "python3_ast_parse": tree is not None,
        "not_generated": not generated,
        "not_vendor": not path_signals["vendor"],
        "not_pathological_repetition": not repetition["heuristic_flag"],
    }

    return {
        "schema_version": 1,
        "kind": "petitgpt_python_document_quality_metrics",
        "contains_source_text": False,
        "content_identity": {
            "raw_sha256": hashlib.sha256(raw).hexdigest(),
            "raw_hash_algorithm": "sha256-raw-bytes-v1",
            "ast_canonical_fingerprint": _ast_fingerprint(tree),
        },
        "size": {
            "raw_bytes": len(raw),
            "text_characters": len(text),
            "line_count": len(lines),
            "nonempty_line_count": len(nonempty_lines),
            "max_line_length": max_line_length,
            "within_200_to_100000_bytes": size_ok,
        },
        "text_fidelity": {
            "utf8_reencode_matches_raw": utf8_round_trip,
            "empty": empty,
            "whitespace_only": whitespace_only,
            "nul_present": nul_present,
            "disallowed_c0_control_count": disallowed_c0_count,
            "disallowed_c0_control_ratio": disallowed_c0_ratio,
            "binary_like": binary_like,
            "binary_like_contract": "NUL present or disallowed C0 control ratio > 0.01",
        },
        "syntax": {
            "python3_ast_parse_ok": tree is not None,
            "error_location_only_no_source": ast_error,
        },
        "path_signals": {
            **path_signals,
            "minified": minified,
            "minified_contract": "nonempty_lines <= 2 and max_line_length >= 500",
        },
        "generated": {
            "heuristic_flag": generated,
            "header_marker_count": generated_marker_count,
            "path_heuristic": path_signals["generated"],
            "detection_only": True,
        },
        "repetition": repetition,
        "comments": comments,
        "docstrings": docstrings,
        "ast_constructs": constructs,
        "imports": imports,
        "boilerplate_descriptors": boilerplate,
        "hard_gates": hard_gates,
        "passes_all_hard_gates": all(hard_gates[gate] for gate in HARD_GATE_ORDER),
    }


def _analysis_size(analysis: Mapping[str, Any]) -> int:
    try:
        value = int(analysis["size"]["raw_bytes"])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError("analysis lacks a valid size.raw_bytes") from exc
    if value < 0:
        raise ValueError("analysis size.raw_bytes cannot be negative")
    return value


def summarize_hard_gate_funnel(
    analyses: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Summarize independent failures and an explicitly ordered hard-gate funnel."""
    prepared: list[tuple[int, dict[str, bool]]] = []
    for analysis in analyses:
        size = _analysis_size(analysis)
        raw_gates = analysis.get("hard_gates")
        if not isinstance(raw_gates, Mapping):
            raise ValueError("analysis lacks hard_gates")
        gates: dict[str, bool] = {}
        for gate in HARD_GATE_ORDER:
            value = raw_gates.get(gate)
            if not isinstance(value, bool):
                raise ValueError(f"hard gate {gate!r} must be boolean")
            gates[gate] = value
        prepared.append((size, gates))

    total_documents = len(prepared)
    total_bytes = sum(size for size, _ in prepared)
    independent: dict[str, Any] = {}
    for gate in HARD_GATE_ORDER:
        passed = [(size, gates) for size, gates in prepared if gates[gate]]
        passed_documents = len(passed)
        passed_bytes = sum(size for size, _ in passed)
        independent[gate] = {
            "passed_documents": passed_documents,
            "passed_raw_bytes": passed_bytes,
            "failed_documents": total_documents - passed_documents,
            "failed_raw_bytes": total_bytes - passed_bytes,
            "pass_rate": _rate(passed_documents, total_documents),
        }

    survivors = prepared
    ordered: list[dict[str, Any]] = []
    for gate in HARD_GATE_ORDER:
        input_documents = len(survivors)
        input_bytes = sum(size for size, _ in survivors)
        passed = [(size, gates) for size, gates in survivors if gates[gate]]
        passed_documents = len(passed)
        passed_bytes = sum(size for size, _ in passed)
        ordered.append({
            "gate": gate,
            "input_documents": input_documents,
            "input_raw_bytes": input_bytes,
            "rejected_at_gate_documents": input_documents - passed_documents,
            "rejected_at_gate_raw_bytes": input_bytes - passed_bytes,
            "passed_documents": passed_documents,
            "passed_raw_bytes": passed_bytes,
        })
        survivors = passed

    retained_documents = len(survivors)
    retained_bytes = sum(size for size, _ in survivors)
    return {
        "schema_version": 1,
        "kind": "petitgpt_python_hard_gate_funnel",
        "hard_gate_order": list(HARD_GATE_ORDER),
        "considered_documents": total_documents,
        "considered_raw_bytes": total_bytes,
        "independent_gate_results": independent,
        "ordered_gate_funnel": ordered,
        "retained_documents": retained_documents,
        "retained_raw_bytes": retained_bytes,
        "retained_document_rate": _rate(retained_documents, total_documents),
        "retained_byte_rate": _rate(retained_bytes, total_bytes),
    }


def wilson_interval(successes: int, total: int) -> dict[str, Any]:
    """Return a deterministic two-sided 95% Wilson binomial interval."""
    if isinstance(successes, bool) or not isinstance(successes, int):
        raise TypeError("successes must be an integer")
    if isinstance(total, bool) or not isinstance(total, int):
        raise TypeError("total must be an integer")
    if total <= 0 or not 0 <= successes <= total:
        raise ValueError("require total > 0 and 0 <= successes <= total")
    z = 1.959963984540054
    proportion = successes / total
    z_squared = z * z
    denominator = 1 + z_squared / total
    center = (proportion + z_squared / (2 * total)) / denominator
    half_width = (
        z
        * math.sqrt(proportion * (1 - proportion) / total + z_squared / (4 * total * total))
        / denominator
    )
    return {
        "method": "wilson_score_two_sided_95_percent_v1",
        "confidence": 0.95,
        "successes": successes,
        "total": total,
        "estimate": proportion,
        "lower": 0.0 if successes == 0 else max(0.0, center - half_width),
        "upper": 1.0 if successes == total else min(1.0, center + half_width),
    }


def _draw_index(*, seed: int, replicate: int, draw: int, size: int) -> int:
    if size <= 0:
        raise ValueError("bootstrap population size must be positive")
    span = 1 << 64
    rejection_limit = span - span % size
    nonce = 0
    while True:
        digest = hashlib.sha256()
        digest.update(_BOOTSTRAP_DOMAIN)
        digest.update(str(seed).encode("ascii"))
        digest.update(b"\0")
        digest.update(str(replicate).encode("ascii"))
        digest.update(b"\0")
        digest.update(str(draw).encode("ascii"))
        digest.update(b"\0")
        digest.update(str(nonce).encode("ascii"))
        value = int.from_bytes(digest.digest()[:8], "big")
        if value < rejection_limit:
            return value % size
        nonce += 1


def _percentile(values: Sequence[float], quantile: float) -> float:
    if not values:
        raise ValueError("cannot calculate a percentile of an empty sequence")
    if not 0 <= quantile <= 1:
        raise ValueError("quantile must be in [0, 1]")
    ordered = sorted(values)
    position = (len(ordered) - 1) * quantile
    lower = math.floor(position)
    upper = math.ceil(position)
    fraction = position - lower
    return ordered[lower] * (1 - fraction) + ordered[upper] * fraction


def _validate_bootstrap(*, seed: int, resamples: int) -> None:
    if isinstance(seed, bool) or not isinstance(seed, int):
        raise TypeError("seed must be an integer")
    if isinstance(resamples, bool) or not isinstance(resamples, int):
        raise TypeError("resamples must be an integer")
    if not 1 <= resamples <= 100_000:
        raise ValueError("resamples must be in [1, 100000]")


def deterministic_bootstrap_mean_interval(
    values: Sequence[int | float],
    *,
    seed: int,
    resamples: int = 2_000,
) -> dict[str, Any]:
    """Return a deterministic SHA-256-indexed percentile bootstrap mean CI."""
    _validate_bootstrap(seed=seed, resamples=resamples)
    numeric = [float(value) for value in values]
    if not numeric:
        raise ValueError("values must not be empty")
    if not all(math.isfinite(value) for value in numeric):
        raise ValueError("values must all be finite")
    replicate_means: list[float] = []
    for replicate in range(resamples):
        total = sum(
            numeric[_draw_index(seed=seed, replicate=replicate, draw=draw, size=len(numeric))]
            for draw in range(len(numeric))
        )
        replicate_means.append(total / len(numeric))
    return {
        "method": "sha256_indexed_percentile_bootstrap_mean_95_percent_v1",
        "confidence": 0.95,
        "seed": seed,
        "resamples": resamples,
        "sample_count": len(numeric),
        "estimate": sum(numeric) / len(numeric),
        "lower": _percentile(replicate_means, 0.025),
        "upper": _percentile(replicate_means, 0.975),
    }


def _estimate_with_interval(point: float, replicates: Sequence[float]) -> dict[str, Any]:
    return {
        "estimate": point,
        "lower_95": _percentile(replicates, 0.025),
        "upper_95": _percentile(replicates, 0.975),
    }


def _break_even_chars_per_token(
    *, projected_characters: float, projected_documents: float, target_tokens: int
) -> float | None:
    content_token_budget = target_tokens - 2 * projected_documents
    if content_token_budget <= 0:
        return None
    return projected_characters / content_token_budget


def estimate_pretokenizer_yield(
    analyses: Sequence[Mapping[str, Any]],
    *,
    population_documents: int,
    seed: int,
    resamples: int = 2_000,
) -> dict[str, Any]:
    """Project local-gate yield without claiming a canonical tokenizer count.

    The input sample is assumed to represent ``population_documents`` with
    equal weight.  Callers using stratified or two-phase samples must construct
    the appropriately weighted analysis sample before invoking this helper.
    """
    _validate_bootstrap(seed=seed, resamples=resamples)
    if isinstance(population_documents, bool) or not isinstance(population_documents, int):
        raise TypeError("population_documents must be an integer")
    if population_documents <= 0:
        raise ValueError("population_documents must be positive")
    if not analyses:
        raise ValueError("analyses must not be empty")

    observations: list[tuple[int, int, int]] = []
    for analysis in analyses:
        raw_bytes = _analysis_size(analysis)
        try:
            text_characters = int(analysis["size"]["text_characters"])
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError("analysis lacks a valid size.text_characters") from exc
        retained = analysis.get("passes_all_hard_gates")
        if not isinstance(retained, bool):
            raise ValueError("analysis passes_all_hard_gates must be boolean")
        if text_characters < 0:
            raise ValueError("analysis size.text_characters cannot be negative")
        observations.append((
            int(retained),
            raw_bytes if retained else 0,
            text_characters if retained else 0,
        ))

    sample_count = len(observations)
    point_documents = population_documents * sum(item[0] for item in observations) / sample_count
    point_bytes = population_documents * sum(item[1] for item in observations) / sample_count
    point_characters = population_documents * sum(item[2] for item in observations) / sample_count

    document_replicates: list[float] = []
    byte_replicates: list[float] = []
    character_replicates: list[float] = []
    for replicate in range(resamples):
        documents = 0
        raw_bytes = 0
        characters = 0
        for draw in range(sample_count):
            item = observations[
                _draw_index(seed=seed, replicate=replicate, draw=draw, size=sample_count)
            ]
            documents += item[0]
            raw_bytes += item[1]
            characters += item[2]
        scale = population_documents / sample_count
        document_replicates.append(documents * scale)
        byte_replicates.append(raw_bytes * scale)
        character_replicates.append(characters * scale)

    retained_count = sum(item[0] for item in observations)
    sensitivity: list[dict[str, Any]] = []
    for ratio in CHARS_PER_TOKEN_SENSITIVITY:
        point = point_characters / ratio + 2 * point_documents
        replicate_values = [
            characters / ratio + 2 * documents
            for characters, documents in zip(character_replicates, document_replicates, strict=True)
        ]
        sensitivity.append({
            "assumed_characters_per_content_token": ratio,
            "includes_bos_and_eos_per_retained_document": True,
            "projected_serialized_token_equivalent": _estimate_with_interval(
                point, replicate_values
            ),
        })

    break_even: list[dict[str, Any]] = []
    for target in YIELD_TARGETS:
        point = _break_even_chars_per_token(
            projected_characters=point_characters,
            projected_documents=point_documents,
            target_tokens=target,
        )
        replicate_values = [
            value
            for characters, documents in zip(character_replicates, document_replicates, strict=True)
            if (
                value := _break_even_chars_per_token(
                    projected_characters=characters,
                    projected_documents=documents,
                    target_tokens=target,
                )
            )
            is not None
        ]
        break_even.append({
            "target_serialized_tokens": target,
            "meaning": (
                "maximum assumed characters per content token that still reaches the target, "
                "including two boundary tokens per retained document"
            ),
            "estimate": point,
            "lower_95": _percentile(replicate_values, 0.025) if replicate_values else None,
            "upper_95": _percentile(replicate_values, 0.975) if replicate_values else None,
            "boundary_tokens_alone_meet_target": point is None,
            "bootstrap_boundary_only_count": resamples - len(replicate_values),
        })

    return {
        "schema_version": 1,
        "kind": "petitgpt_python_pretokenizer_yield_sensitivity",
        "scope": "PRE_TOKENIZER_SENSITIVITY_ONLY_NOT_A_CANONICAL_TOKEN_COUNT",
        "canonical_tokenizer_used": False,
        "final_token_quota_supported": False,
        "sampling_assumption": "input analyses are equal-weight representatives of population_documents",
        "bootstrap": {
            "method": "sha256_indexed_joint_percentile_bootstrap_95_percent_v1",
            "seed": seed,
            "resamples": resamples,
            "confidence": 0.95,
        },
        "sample": {
            "documents": sample_count,
            "retained_documents": retained_count,
            "retained_fraction_wilson_95": wilson_interval(retained_count, sample_count),
        },
        "population_documents": population_documents,
        "projected_retained_documents": _estimate_with_interval(
            point_documents, document_replicates
        ),
        "projected_retained_raw_bytes": _estimate_with_interval(point_bytes, byte_replicates),
        "projected_retained_characters": _estimate_with_interval(
            point_characters, character_replicates
        ),
        "serialized_token_sensitivity": sensitivity,
        "break_even_characters_per_content_token": break_even,
        "limitations": [
            "No tokenizer was used; token values are sensitivity scenarios, not measured counts.",
            "Only the local hard gates represented in the input analyses are modeled.",
            "Near-deduplication, decontamination, repository caps, and later selection can reduce yield.",
        ],
    }
